import { join } from "node:path";
import { readFile } from "node:fs/promises";
import type { NeuralNetwork } from "@superhumaan/dna-config";
import { NEURAL_NETWORK_FILE, NEURAL_NETWORK_ALT } from "@superhumaan/dna-config";
import { fileExists, readJsonFile } from "./fs.js";
import { NeuralNetworkSchema } from "@superhumaan/dna-config";
import { ensureKnowledgeForContext } from "./marketplace/ensure.js";
import { ensureProjectUiStandards } from "./ivf/ui-standards.js";
import { TARGET_INTENTS, type ContextTarget } from "./context-intents.js";
import { generateMethodologyContext } from "./delivery/context.js";

export type { ContextTarget };

const TARGET_BEHAVIOUR: Record<ContextTarget, string[]> = {
  cursor: ["ai.behaviour.md", "coding.behaviour.md"],
  claude: ["ai.behaviour.md", "coding.behaviour.md", "testing.behaviour.md"],
  chatgpt: ["ai.behaviour.md", "documentation.behaviour.md"],
  copilot: ["ai.behaviour.md", "coding.behaviour.md", "testing.behaviour.md"],
  windsurf: ["ai.behaviour.md", "coding.behaviour.md"],
  gemini: ["ai.behaviour.md", "documentation.behaviour.md"],
  backend: ["coding.behaviour.md", "security.behaviour.md", "runtime.behaviour.md"],
  frontend: ["coding.behaviour.md", "testing.behaviour.md"],
  security: ["security.behaviour.md", "runtime.behaviour.md"],
  qa: ["testing.behaviour.md", "documentation.behaviour.md"],
  devops: ["runtime.behaviour.md", "coding.behaviour.md"],
  rbac: ["security.behaviour.md", "ai.behaviour.md", "coding.behaviour.md", "testing.behaviour.md"],
  platform: ["ai.behaviour.md", "security.behaviour.md", "coding.behaviour.md", "documentation.behaviour.md"],
  compliance: ["security.behaviour.md", "documentation.behaviour.md", "ai.behaviour.md", "coding.behaviour.md"],
  legal: ["security.behaviour.md", "documentation.behaviour.md", "ai.behaviour.md", "coding.behaviour.md"],
  multilingual: ["ai.behaviour.md", "documentation.behaviour.md"],
  methodology: ["delivery.behaviour.md", "documentation.behaviour.md", "ai.behaviour.md"],
  ivf: ["ai.behaviour.md", "documentation.behaviour.md", "security.behaviour.md", "coding.behaviour.md"],
  all: [],
};

export async function generateContext(root: string, target: ContextTarget): Promise<string> {
  const dnaDir = join(root, ".DNA");
  if (!(await fileExists(dnaDir))) {
    throw new Error(
      `No .DNA/ directory at ${root}.\n` +
        `Run \`dna init\` first, or omit --cwd when your shell is already in the project.`,
    );
  }

  if (target === "methodology") {
    return generateMethodologyContext(root);
  }

  if (target === "cursor" || target === "frontend" || target === "ivf" || target === "copilot" || target === "windsurf") {
    await ensureProjectUiStandards({ root, includeSharedLibrary: false });
  }

  let neuralPath = join(root, NEURAL_NETWORK_FILE);
  if (!(await fileExists(neuralPath))) {
    neuralPath = join(root, NEURAL_NETWORK_ALT);
  }
  const neuralRaw = await readJsonFile<unknown>(neuralPath);
  const neuralParsed = NeuralNetworkSchema.safeParse(neuralRaw);
  const neuralNetwork: NeuralNetwork | null = neuralParsed.success ? neuralParsed.data : null;

  await ensureKnowledgeForContext(root, target, neuralNetwork);

  const sections: string[] = [
    "# DNA Context",
    `Target: ${target}`,
    "",
    "_Generated by DNA by Humaan. Git remembers your code. DNA remembers your system._",
    "",
  ];

  const behaviourFiles =
    TARGET_BEHAVIOUR[target].length > 0
      ? TARGET_BEHAVIOUR[target]
      : [
          "ai.behaviour.md",
          "coding.behaviour.md",
          "testing.behaviour.md",
          "security.behaviour.md",
        ];

  sections.push("## Behaviour\n");
  for (const file of behaviourFiles) {
    const path = join(root, ".DNA", "behaviour", file);
    if (await fileExists(path)) {
      const content = await readFile(path, "utf-8");
      sections.push(`### ${file}\n`, content, "\n");
    }
  }

  if (neuralNetwork) {
    const intents =
      target === "all"
        ? Object.values(neuralNetwork.intents)
        : (TARGET_INTENTS[target] ?? [])
            .map((name) => neuralNetwork.intents[name])
            .filter(Boolean);

    if (intents.length > 0) {
      sections.push("## Relevant Intents (neuralNetwork)\n");
      for (const intent of intents) {
        sections.push(`### ${intent.intent}`, intent.description, "");
        sections.push(`Knowledge: ${intent.requiredKnowledge.join(", ")}`);
        sections.push(`Behaviour: ${intent.requiredBehaviour.join(", ")}`);
        sections.push(`Memory: ${intent.cellularMemory.join(", ")}`);
        sections.push(`Impressions: ${intent.impressions.join(", ")}`);
        sections.push("");
      }
    }

    const knowledgePaths = new Set<string>();
    for (const intent of intents) {
      intent.requiredKnowledge.forEach((k) => knowledgePaths.add(k));
    }

    if (knowledgePaths.size > 0) {
      sections.push("## Knowledge\n");
      for (const kPath of knowledgePaths) {
        const fullPath = join(root, ".DNA", "knowledge", kPath);
        if (await fileExists(fullPath)) {
          const content = await readFile(fullPath, "utf-8");
          sections.push(`### ${kPath}\n`, content, "\n");
        }
      }
    }
  }

  const memoryFiles = [
    "hippocampus/project-summary.md",
    "prefrontalCortex/current-plan.md",
    "prefrontalCortex/next-actions.md",
    "prefrontalCortex/feature-building-rules.md",
    "prefrontalCortex/rbac-permission-matrix.md",
    "prefrontalCortex/compliance-control-matrix.md",
    "prefrontalCortex/legal-considerations-matrix.md",
    "occipitalLobe/ui-patterns.md",
    "occipitalLobe/feature-templates.md",
    "amygdala/risks.md",
  ];

  sections.push("## CellularMemory\n");
  for (const mem of memoryFiles) {
    const path = join(root, ".DNA", "CellularMemory", mem);
    if (await fileExists(path)) {
      const content = await readFile(path, "utf-8");
      sections.push(`### ${mem}\n`, content, "\n");
    }
  }

  return sections.join("\n");
}
