import { join } from "node:path";
import { readFile } from "node:fs/promises";
import type { NeuralNetwork } from "@humaan/dna-config";
import { NEURAL_NETWORK_FILE, NEURAL_NETWORK_ALT } from "@humaan/dna-config";
import { fileExists, readJsonFile } from "./fs.js";
import { NeuralNetworkSchema } from "@humaan/dna-config";

export type ContextTarget =
  | "cursor"
  | "claude"
  | "chatgpt"
  | "copilot"
  | "windsurf"
  | "gemini"
  | "backend"
  | "frontend"
  | "security"
  | "qa"
  | "devops"
  | "rbac"
  | "all";

const TARGET_INTENTS: Record<ContextTarget, string[]> = {
  cursor: ["build_frontend_component", "create_api_endpoint", "install_dependency", "create_pr"],
  claude: ["build_frontend_component", "create_api_endpoint", "fix_runtime_error", "create_pr"],
  chatgpt: ["review_architecture", "update_documentation", "investigate_bug"],
  copilot: ["build_frontend_component", "create_api_endpoint", "create_pr"],
  windsurf: ["build_frontend_component", "fix_runtime_error", "create_pr"],
  gemini: ["review_architecture", "update_documentation", "investigate_bug"],
  backend: ["create_api_endpoint", "fix_runtime_error", "configure_ci_cd"],
  frontend: ["build_frontend_component", "build_pwa", "create_mobile_feature"],
  security: ["implement_rbac", "add_authentication", "improve_security"],
  qa: ["write_tests", "investigate_bug"],
  devops: ["configure_ci_cd", "fix_runtime_error"],
  rbac: ["implement_rbac"],
  all: [],
};

const TARGET_BEHAVIOUR: Record<ContextTarget, string[]> = {
  cursor: ["ai.behaviour.md", "coding.behaviour.md"],
  claude: ["ai.behaviour.md", "coding.behaviour.md", "testing.behaviour.md"],
  chatgpt: ["ai.behaviour.md", "documentation.behaviour.md"],
  copilot: ["ai.behaviour.md", "coding.behaviour.md", "testing.behaviour.md"],
  windsurf: ["ai.behaviour.md", "coding.behaviour.md"],
  gemini: ["ai.behaviour.md", "documentation.behaviour.md"],
  backend: ["coding.behaviour.md", "security.behaviour.md", "runtime.behaviour.md"],
  frontend: ["coding.behaviour.md", "testing.behaviour.md"],
  security: ["security.behaviour.md", "runtime.behaviour.md"],
  qa: ["testing.behaviour.md", "documentation.behaviour.md"],
  devops: ["runtime.behaviour.md", "coding.behaviour.md"],
  rbac: ["security.behaviour.md", "ai.behaviour.md", "coding.behaviour.md", "testing.behaviour.md"],
  all: [],
};

export async function generateContext(root: string, target: ContextTarget): Promise<string> {
  let neuralPath = join(root, NEURAL_NETWORK_FILE);
  if (!(await fileExists(neuralPath))) {
    neuralPath = join(root, NEURAL_NETWORK_ALT);
  }
  const neuralRaw = await readJsonFile<unknown>(neuralPath);
  const neuralParsed = NeuralNetworkSchema.safeParse(neuralRaw);
  const neuralNetwork: NeuralNetwork | null = neuralParsed.success ? neuralParsed.data : null;

  const sections: string[] = [
    "# DNA Context",
    `Target: ${target}`,
    "",
    "_Generated by DNA by Humaan. Git remembers your code. DNA remembers your system._",
    "",
  ];

  const behaviourFiles =
    TARGET_BEHAVIOUR[target].length > 0
      ? TARGET_BEHAVIOUR[target]
      : [
          "ai.behaviour.md",
          "coding.behaviour.md",
          "testing.behaviour.md",
          "security.behaviour.md",
        ];

  sections.push("## Behaviour\n");
  for (const file of behaviourFiles) {
    const path = join(root, ".DNA", "behaviour", file);
    if (await fileExists(path)) {
      const content = await readFile(path, "utf-8");
      sections.push(`### ${file}\n`, content, "\n");
    }
  }

  if (neuralNetwork) {
    const intents =
      target === "all"
        ? Object.values(neuralNetwork.intents)
        : (TARGET_INTENTS[target] ?? [])
            .map((name) => neuralNetwork.intents[name])
            .filter(Boolean);

    if (intents.length > 0) {
      sections.push("## Relevant Intents (neuralNetwork)\n");
      for (const intent of intents) {
        sections.push(`### ${intent.intent}`, intent.description, "");
        sections.push(`Knowledge: ${intent.requiredKnowledge.join(", ")}`);
        sections.push(`Behaviour: ${intent.requiredBehaviour.join(", ")}`);
        sections.push(`Memory: ${intent.cellularMemory.join(", ")}`);
        sections.push(`Impressions: ${intent.impressions.join(", ")}`);
        sections.push("");
      }
    }

    const knowledgePaths = new Set<string>();
    for (const intent of intents) {
      intent.requiredKnowledge.forEach((k) => knowledgePaths.add(k));
    }

    if (knowledgePaths.size > 0) {
      sections.push("## Knowledge\n");
      for (const kPath of knowledgePaths) {
        const fullPath = join(root, ".DNA", "knowledge", kPath);
        if (await fileExists(fullPath)) {
          const content = await readFile(fullPath, "utf-8");
          sections.push(`### ${kPath}\n`, content, "\n");
        }
      }
    }
  }

  const memoryFiles = [
    "hippocampus/project-summary.md",
    "prefrontalCortex/current-plan.md",
    "prefrontalCortex/next-actions.md",
    "prefrontalCortex/rbac-permission-matrix.md",
    "amygdala/risks.md",
  ];

  sections.push("## CellularMemory\n");
  for (const mem of memoryFiles) {
    const path = join(root, ".DNA", "CellularMemory", mem);
    if (await fileExists(path)) {
      const content = await readFile(path, "utf-8");
      sections.push(`### ${mem}\n`, content, "\n");
    }
  }

  return sections.join("\n");
}
