# DNA by Humaan — sponsorship
# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

custom:
  - https://dna.humaan.app
