# DNA by Humaan — sponsorship & attribution
# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

custom:
  - https://humaan.com
  - https://superlite.ai
  - https://dna.humaan.app
