import { join } from "node:path";
import type { DnaConfig } from "@superhumaan/dna-config";
import { DNA_CONFIG_FILE } from "@superhumaan/dna-config";
import { readFile } from "node:fs/promises";
import { writeFileEnsured, writeJsonFile } from "../fs.js";
import { loadDnaConfig } from "../validator.js";
import { ensureKnowledgeInstalled } from "../marketplace/ensure.js";
import {
  getIndustryMeta,
  knowledgePackIdsForIndustry,
  knowledgePathsForIndustry,
  parseIndustryInput,
  type IndustrySector,
} from "./catalog.js";

export interface IndustryPlanOptions {
  root: string;
  sector?: string;
  clientName?: string;
  secondary?: string;
  quote?: string;
}

export interface IndustryPlanResult {
  planPath: string;
  summaryPath: string;
  context: string;
  sector: IndustrySector;
  linkedPacks: string[];
}

export async function setActiveIndustry(
  root: string,
  sector: IndustrySector,
  options?: { clientName?: string; secondary?: IndustrySector[] },
): Promise<DnaConfig> {
  const config = (await loadDnaConfig(root))!;
  const updated: DnaConfig = {
    ...config,
    industry: {
      active: sector,
      secondary: options?.secondary ?? config.industry?.secondary ?? [],
      clientName: options?.clientName ?? config.industry?.clientName,
    },
    updatedAt: new Date().toISOString(),
  };
  await writeJsonFile(join(root, DNA_CONFIG_FILE), updated);
  return updated;
}

export async function generateIndustryPlan(options: IndustryPlanOptions): Promise<IndustryPlanResult> {
  const config = await loadDnaConfig(options.root);
  const sector = options.sector
    ? parseIndustryInput(options.sector)
    : config?.industry?.active
      ? config.industry.active
      : (() => {
          throw new Error("Specify industry sector: dna plan industry <sector>");
        })();

  const secondary = options.secondary
    ? options.secondary.split(",").map((s) => parseIndustryInput(s.trim()))
    : undefined;

  await setActiveIndustry(options.root, sector, {
    clientName: options.clientName,
    secondary,
  });

  const meta = getIndustryMeta(sector);
  const packIds = knowledgePackIdsForIndustry(sector);
  await ensureKnowledgeInstalled(options.root, packIds, config?.channel ?? "stable");

  const knowledgePaths = knowledgePathsForIndustry(sector);
  const knowledgeSections: string[] = [];
  for (const kPath of knowledgePaths) {
    const fullPath = join(options.root, ".DNA", "knowledge", kPath);
    try {
      const content = await readFile(fullPath, "utf-8");
      knowledgeSections.push(`### ${kPath}\n`, content, "");
    } catch {
      knowledgeSections.push(`### ${kPath}\n`, "_Pack not yet installed — run dna marketplace install " + meta.packId + "_\n");
    }
  }

  const lines = [
    "# Industry Plan",
    "",
    `_Generated by DNA. Load with \`dna context industry\` before feature work._`,
    "",
    `**Sector:** ${meta.name} (\`${sector}\`)`,
    options.clientName ? `**Client:** ${options.clientName}` : "",
    config?.projectName ? `**Project:** ${config.projectName}` : "",
    "",
    options.quote ? `## User request\n\n${options.quote}\n` : "",
    "## Linked marketplace packs",
    "",
    ...meta.linkedPacks.map((p) => `- \`${p}\``),
    "",
    "## AI rules for this industry",
    "",
    "1. Run `dna context industry` at the start of each session",
    "2. Follow practices and regulation files — flag compliance gaps before coding",
    "3. Apply UI patterns from `ui-patterns.dna.md` unless client brand guide overrides",
    "4. For agencies: use `agency-notes.dna.md` tone and scope discipline",
    "5. Code delivery still follows DNA quality gates",
    "",
    "## Industry knowledge",
    "",
    ...knowledgeSections,
  ];

  const context = lines.filter(Boolean).join("\n");
  const planPath = join(
    options.root,
    ".DNA",
    "CellularMemory",
    "prefrontalCortex",
    "industry-plan.md",
  );
  const summaryPath = join(
    options.root,
    ".DNA",
    "CellularMemory",
    "hippocampus",
    "industry-summary.md",
  );

  await writeFileEnsured(planPath, context);
  await writeFileEnsured(
    summaryPath,
    `# Industry — ${meta.name}\n\nActive sector: **${sector}**\n\n${meta.description}\n\nLinked packs: ${meta.linkedPacks.join(", ")}\n\n_Last updated: ${new Date().toISOString()}_\n`,
  );

  return {
    planPath,
    summaryPath,
    context,
    sector,
    linkedPacks: meta.linkedPacks,
  };
}
