import { join } from "node:path";
import { readFile } from "node:fs/promises";
import type { DnaConfig } from "@superhumaan/dna-config";
import { writeFileEnsured, fileExists } from "../fs.js";
import { loadDnaConfig } from "../validator.js";
import { ensureKnowledgeInstalled } from "../marketplace/ensure.js";
import { resolveFeaturePlanPackIds } from "./knowledge.js";
import {
  PLATFORM_FEATURES,
  DNA_REFERENCE_PROJECT_DEFS,
  getFeature,
  featuresForProject,
  type PlatformFeature,
} from "./catalog.js";
import {
  formatCodeReference,
  getReferenceProject,
  type ReferenceProject,
} from "./reference-projects.js";

export interface FeaturePlanOptions {
  root: string;
  featureId: string;
  quote?: string;
  /** Reference a DNA production project for patterns */
  referenceProject?: "aistudio" | "colorparty" | "humaan" | "soli";
}

export interface FeaturePlanResult {
  planPath: string;
  context: string;
  feature: PlatformFeature;
}

const PHASE_TEMPLATES: Record<string, string[]> = {
  auth: [
    "Define auth model (OAuth, B2C, local OTP) and session strategy",
    "Implement server session/JWT with httpOnly cookies",
    "Add route guards (client) and middleware (server)",
    "Wire admin role resolution and capability gates",
    "Add MFA/OTP if required",
    "Verification: login, refresh, logout, role switch",
  ],
  admin: [
    "Scaffold admin shell with nav groups (General, Directory, Security, Data, Logging)",
    "Implement directory/users CRUD with invite flow",
    "Add settings pages per domain",
    "Wire requireAdmin middleware on all admin APIs",
    "Hide admin nav from non-admin roles in main app",
    "Audit log for admin mutations",
  ],
  integration: [
    "Document integration contract (auth, scopes, webhooks)",
    "Implement server-side client with secrets in env only",
    "Add sync jobs / cron with idempotency",
    "Admin UI for connection status and manual sync",
    "Error handling and rate limits",
    "Verification: sync dry-run, failure recovery",
  ],
  cloud: [
    "Choose target (Azure Container Apps / AWS ECS / Vercel)",
    "Infrastructure as code (Terraform or vercel.json)",
    "Secrets in Key Vault / Secrets Manager / Vercel env",
    "CI/CD pipeline with smoke tests",
    "Health checks and observability",
    "Rollback procedure documented",
  ],
  product: [
    "Define data model and API contracts",
    "Implement server persistence with validation",
    "Build UI with loading/error/empty states",
    "Add RBAC gates per feature",
    "Write tests for core flows",
    "Update Impressions architecture docs",
  ],
  ai: [
    "Server-proxy all model calls — keys never in browser",
    "Content policy + input guard pipeline",
    "Usage quotas and rate limits",
    "Audit without storing raw prompts",
    "Admin governance UI",
    "Red-team test blocked inputs",
  ],
  ops: [
    "Define metrics and report schema",
    "Implement aggregation queries / cron",
    "Build manager-facing dashboard",
    "Permission-gate reports by role",
    "Export capability",
    "Validate numbers against source system",
  ],
};

function buildFeatureBrief(
  feature: PlatformFeature,
  options: FeaturePlanOptions,
  config: DnaConfig | null,
  installedPacks: string[],
  project: ReferenceProject | undefined,
): string {
  const phases = PHASE_TEMPLATES[feature.category] ?? PHASE_TEMPLATES.product;
  const refProject = options.referenceProject ?? feature.sourceProjects[0];

  const lines = [
    `# DNA Feature Plan: ${feature.name}`,
    "",
    "_Generated by DNA by Humaan. Give this entire document to your AI tool before building._",
    "",
    "## User requirement",
    "",
    options.quote?.trim() || `Implement ${feature.name} for ${config?.projectName ?? "this project"}.`,
    "",
    "## Feature",
    "",
    `- **ID:** ${feature.id}`,
    `- **Category:** ${feature.category}`,
    `- **Description:** ${feature.description}`,
    `- **Reference project:** ${project?.name ?? refProject} (${project?.stack ?? "see DNA catalog"})`,
    "",
    "## DNA production reference",
    "",
    "DNA has shipped this in production. Study these patterns before improvising:",
    "",
    ...(project?.highlights.map((h) => `- ${h}`) ?? ["- See platform catalog"]),
    "",
    ...(feature.referencePaths && refProject && feature.referencePaths[refProject]
      ? [`**Code reference:** ${formatCodeReference(project, feature.referencePaths[refProject])}`]
      : []),
    "",
    "## Knowledge to load (mandatory)",
    "",
    ...feature.knowledgeFiles.map((k) => `- \`.DNA/knowledge/${k}\``),
    "",
    ...(installedPacks.length
      ? [
          "## Installed knowledge packs",
          "",
          ...installedPacks.map((p) => `- \`${p}\``),
          "",
        ]
      : []),
    "- `.DNA/behaviour/security.behaviour.md`",
    "- `.DNA/workflows/rbac.workflow.md` (if access control involved)",
    `- \`.DNA/neuralNetwork.json\` → intent implement_${feature.id.replace(/-/g, "_")} or closest match`,
    "",
    "## Implementation phases",
    "",
    ...phases.map((p, i) => `${i + 1}. ${p}`),
    "",
    "## Cross-cutting requirements (all DNA features)",
    "",
    "### Access control",
    "- Permission matrix before UI work (`dna plan rbac` if roles involved)",
    "- Server enforcement + route guards + menu/notification hiding",
    "",
    "### Admin portal",
    "- If feature is admin-configurable, add admin screen under `/admin` or `/app/admin`",
    "- requireAdmin on API; hide nav items from non-admins",
    "",
    "### Directory & identity",
    "- Google Directory or Azure AD B2C — never duplicate user records manually",
    "- Domain lock for employee-only apps",
    "",
    "### Integrations",
    "- Secrets in env / Key Vault only",
    "- Cron jobs idempotent with logging",
    "- Admin manual sync button",
    "",
    "### Feature flags",
    "- Env toggle for risky rollout; admin KV for per-tenant flags",
    "- Default off in production until verified",
    "",
    "### Audit",
    "- Log admin mutations and security events",
    "- Never log secrets or raw AI prompts",
    "",
    "## Definition of done",
    "",
    `- [ ] Feature works for all intended roles`,
    `- [ ] Unauthorized users cannot see OR use restricted surfaces`,
    `- [ ] Admin can configure/manage the feature`,
    `- [ ] Tests cover happy path + permission denial`,
    `- [ ] Impressions/security docs updated`,
    `- [ ] \`dna validate\` passes`,
    "",
    "## Related features in DNA stack",
    "",
    ...PLATFORM_FEATURES.filter(
      (f) =>
        f.id !== feature.id &&
        f.sourceProjects.some((p) => feature.sourceProjects.includes(p)),
    )
      .slice(0, 8)
      .map((f) => `- ${f.id}: ${f.name}`),
    "",
  ];

  return lines.join("\n");
}

export async function generateFeaturePlan(options: FeaturePlanOptions): Promise<FeaturePlanResult> {
  const feature = getFeature(options.featureId);
  if (!feature) {
    const ids = PLATFORM_FEATURES.map((f) => f.id).join(", ");
    throw new Error(`Unknown feature: ${options.featureId}. Available: ${ids}`);
  }

  const config = await loadDnaConfig(options.root);
  if (!config) {
    throw new Error("DNA not installed. Run `dna init` first.");
  }

  // Layer 3: prefetch all knowledge before writing the plan
  const packIds = resolveFeaturePlanPackIds(feature);
  const ensureResult = await ensureKnowledgeInstalled(options.root, packIds, config.channel);
  const installedPacks = [...ensureResult.installed, ...ensureResult.refreshed];

  const refProject = options.referenceProject ?? feature.sourceProjects[0];
  const project = refProject ? await getReferenceProject(refProject) : undefined;
  const context = buildFeatureBrief(feature, options, config, installedPacks, project);
  const slug = feature.id;
  const planPath = join(options.root, ".DNA", "plans", `feature-${slug}.md`);
  await writeFileEnsured(planPath, context);

  return { planPath, context, feature };
}

export async function loadFeatureKnowledgeSnippet(
  root: string,
  knowledgePath: string,
): Promise<string | null> {
  const full = join(root, ".DNA", "knowledge", knowledgePath);
  if (!(await fileExists(full))) return null;
  return readFile(full, "utf-8");
}

export function formatPlatformCatalog(): string {
  const lines = [
    "DNA Platform Feature Catalog",
    "===============================",
    "",
    "Production projects DNA learned from:",
    "",
  ];

  for (const p of DNA_REFERENCE_PROJECT_DEFS) {
    lines.push(`• ${p.id} — ${p.name}`);
    lines.push(`  ${p.stack}`);
    for (const h of p.highlights.slice(0, 3)) {
      lines.push(`  - ${h}`);
    }
    lines.push("");
  }

  lines.push("Features (dna plan feature <id>):", "");
  const byCategory = new Map<string, PlatformFeature[]>();
  for (const f of PLATFORM_FEATURES) {
    const list = byCategory.get(f.category) ?? [];
    list.push(f);
    byCategory.set(f.category, list);
  }

  for (const [cat, features] of byCategory) {
    lines.push(`[${cat}]`);
    for (const f of features) {
      lines.push(`  ${f.id.padEnd(28)} ${f.name}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

export function formatProjectFeatures(projectId: "aistudio" | "colorparty" | "humaan" | "soli"): string {
  const project = DNA_REFERENCE_PROJECT_DEFS.find((p) => p.id === projectId);
  if (!project) return `Unknown project: ${projectId}`;

  const features = featuresForProject(projectId);
  const lines = [
    `${project.name} — DNA Feature Map`,
    "=".repeat(40),
    "",
    project.stack,
    "",
    "Features to reference when building similar systems:",
    "",
  ];

  for (const f of features) {
    lines.push(`• ${f.id}`);
    lines.push(`  ${f.description}`);
    lines.push(`  dna plan feature ${f.id} --reference-project ${projectId}`);
    lines.push("");
  }

  return lines.join("\n");
}

export {
  PLATFORM_FEATURES,
  DNA_REFERENCE_PROJECT_DEFS,
  getFeature,
  featuresForProject,
};
