/**
 * DNA stack archetypes — approved system shapes with compatibility rules.
 * AI and validation use this to avoid incoherent technology mixes.
 */

export type StackPlatform = "web" | "mobile" | "desktop" | "cms";

export interface StackArchetype {
  id: string;
  name: string;
  description: string;
  platform: StackPlatform;
  layers: {
    language: string[];
    frontend?: string[];
    bundler?: string[];
    backend?: string[];
    testing?: string[];
    database?: string[];
    hosting?: string[];
  };
  /** Technology ids that must NOT appear in this project */
  excludes: string[];
  /** Marketplace pack ids installed at init */
  knowledgePacks: string[];
  runtimeAdapters?: string[];
  referenceProjects?: string[];
}

export interface StackConflict {
  technologies: string[];
  reason: string;
  severity: "error" | "warning";
}

export const STACK_ARCHETYPES: StackArchetype[] = [
  {
    id: "react-vite-api",
    name: "React SPA + API",
    description:
      "React single-page app with Vite, separate Express or Fastify API. ColorParty-style DNA web pattern.",
    platform: "web",
    layers: {
      language: ["typescript", "javascript"],
      frontend: ["react"],
      bundler: ["vite"],
      backend: ["express", "fastify"],
      testing: ["vitest", "playwright", "jest"],
      database: ["postgresql", "sqlite", "supabase", "mysql", "mongodb"],
      hosting: ["vercel", "railway", "azure", "aws"],
    },
    excludes: ["next", "nestjs", "ghost", "vue", "svelte", "angular", "nuxt"],
    knowledgePacks: ["frameworks/vite", "frameworks/react", "frameworks/express", "disciplines/security"],
    runtimeAdapters: ["express", "fastify"],
    referenceProjects: ["colorparty", "humaan"],
  },
  {
    id: "vercel-supabase",
    name: "Vercel + Supabase",
    description: "React + Vite frontend, Express API on Vercel, Supabase Postgres. DNA Ops pattern.",
    platform: "web",
    layers: {
      language: ["typescript", "javascript"],
      frontend: ["react"],
      bundler: ["vite"],
      backend: ["express", "fastify"],
      testing: ["vitest", "playwright"],
      database: ["supabase", "postgresql"],
      hosting: ["vercel"],
    },
    excludes: ["next", "nestjs", "ghost", "vue", "svelte"],
    knowledgePacks: ["frameworks/vite", "frameworks/react", "platforms/b2b-saas", "disciplines/security"],
    runtimeAdapters: ["express"],
    referenceProjects: ["humaan", "colorparty"],
  },
  {
    id: "next-fullstack",
    name: "Next.js Full-Stack",
    description:
      "Next.js App Router with built-in bundler. Use route handlers — do not add Vite or a separate Express server for the same app.",
    platform: "web",
    layers: {
      language: ["typescript", "javascript"],
      frontend: ["next"],
      bundler: ["next"],
      backend: ["next"],
      testing: ["vitest", "jest", "playwright"],
      database: ["postgresql", "sqlite", "supabase", "mysql"],
      hosting: ["vercel"],
    },
    excludes: ["vite", "express", "fastify", "nestjs", "ghost", "react-spa", "vue", "svelte"],
    knowledgePacks: ["frameworks/nextjs", "frameworks/react", "disciplines/security"],
    runtimeAdapters: ["next"],
  },
  {
    id: "nestjs-modular",
    name: "NestJS Modular API",
    description:
      "NestJS backend with modules, guards, and DTOs. Pair with a separate React SPA (react-vite-api) in monorepo if needed.",
    platform: "web",
    layers: {
      language: ["typescript"],
      frontend: ["react"],
      bundler: ["vite"],
      backend: ["nestjs"],
      testing: ["jest", "vitest"],
      database: ["postgresql", "mysql", "mongodb"],
      hosting: ["azure", "aws", "railway"],
    },
    excludes: ["next", "express", "fastify", "ghost"],
    knowledgePacks: ["frameworks/nestjs", "frameworks/vite", "frameworks/react", "frameworks/express", "disciplines/security"],
    runtimeAdapters: ["nestjs"],
  },
  {
    id: "mobile-expo",
    name: "React Native / Expo",
    description: "Mobile app with React Native or Expo. Backend is separate API or BaaS.",
    platform: "mobile",
    layers: {
      language: ["typescript", "javascript"],
      frontend: ["react-native"],
      bundler: ["metro"],
      backend: ["express", "fastify", "supabase"],
      testing: ["jest", "vitest"],
      database: ["supabase", "postgresql", "sqlite"],
      hosting: ["eas", "vercel"],
    },
    excludes: ["next", "vite", "ghost", "vue", "svelte", "nestjs"],
    knowledgePacks: ["frameworks/react-native", "disciplines/mobile-development", "disciplines/security"],
  },
  {
    id: "ghost-cms",
    name: "Ghost CMS",
    description:
      "Standalone Ghost blog/CMS. Uses Ghost themes (Handlebars) — not React, Vite, or a custom SPA in the same codebase.",
    platform: "cms",
    layers: {
      language: ["javascript"],
      frontend: ["ghost"],
      bundler: ["ghost"],
      backend: ["ghost"],
      testing: [],
      database: ["sqlite", "mysql", "postgresql"],
      hosting: ["ghost-pro", "azure", "aws"],
    },
    excludes: ["react", "vite", "next", "vue", "svelte", "express", "fastify", "nestjs"],
    knowledgePacks: ["frameworks/ghost", "cms/ghost", "disciplines/security"],
  },
  {
    id: "vue-vite-api",
    name: "Vue SPA + API",
    description: "Vue 3 SPA with Vite and Express or Fastify API.",
    platform: "web",
    layers: {
      language: ["typescript", "javascript"],
      frontend: ["vue"],
      bundler: ["vite"],
      backend: ["express", "fastify"],
      testing: ["vitest", "playwright"],
      database: ["postgresql", "sqlite", "mysql"],
      hosting: ["vercel", "railway"],
    },
    excludes: ["next", "react", "svelte", "ghost", "nestjs"],
    knowledgePacks: ["frameworks/vite", "frameworks/vue", "disciplines/security"],
    runtimeAdapters: ["express", "fastify"],
  },
  {
    id: "svelte-vite-api",
    name: "Svelte SPA + API",
    description: "Svelte or SvelteKit-lite SPA with Vite and API backend.",
    platform: "web",
    layers: {
      language: ["typescript", "javascript"],
      frontend: ["svelte"],
      bundler: ["vite"],
      backend: ["express", "fastify"],
      testing: ["vitest", "playwright"],
      database: ["postgresql", "sqlite"],
      hosting: ["vercel", "railway"],
    },
    excludes: ["next", "react", "vue", "ghost", "nestjs"],
    knowledgePacks: ["frameworks/vite", "frameworks/svelte", "disciplines/security"],
    runtimeAdapters: ["express", "fastify"],
  },
  {
    id: "pwa-react-vite",
    name: "React PWA",
    description: "Installable progressive web app with Vite + React and optional API backend.",
    platform: "web",
    layers: {
      language: ["typescript", "javascript"],
      frontend: ["react"],
      bundler: ["vite"],
      backend: ["express", "fastify"],
      testing: ["vitest", "playwright"],
      database: ["postgresql", "sqlite", "supabase"],
      hosting: ["vercel", "railway", "azure"],
    },
    excludes: ["next", "nestjs", "ghost", "vue", "svelte"],
    knowledgePacks: ["frameworks/vite", "frameworks/react", "platforms/pwa", "disciplines/security"],
    runtimeAdapters: ["express", "fastify"],
  },
  {
    id: "desktop-electron",
    name: "Electron Desktop",
    description: "Cross-platform desktop app (Windows, macOS, Linux) with Electron and React.",
    platform: "desktop",
    layers: {
      language: ["typescript", "javascript"],
      frontend: ["react"],
      bundler: ["vite"],
      backend: ["express"],
      testing: ["vitest", "playwright"],
      database: ["sqlite", "postgresql"],
      hosting: ["github-releases", "azure"],
    },
    excludes: ["next", "nestjs", "ghost", "vue", "svelte", "react-native"],
    knowledgePacks: ["platforms/desktop-cross-platform", "frameworks/react", "frameworks/vite", "disciplines/security"],
  },
  {
    id: "desktop-tauri",
    name: "Tauri Desktop",
    description: "Lightweight desktop app with Tauri shell and web frontend.",
    platform: "desktop",
    layers: {
      language: ["typescript", "javascript", "rust"],
      frontend: ["react", "svelte", "vue"],
      bundler: ["vite"],
      testing: ["vitest", "playwright"],
      database: ["sqlite", "postgresql"],
      hosting: ["github-releases"],
    },
    excludes: ["next", "nestjs", "ghost", "react-native", "electron"],
    knowledgePacks: ["platforms/desktop-cross-platform", "frameworks/react", "frameworks/vite", "disciplines/security"],
  },
  {
    id: "browser-extension-chrome",
    name: "Chrome Extension",
    description: "Manifest V3 browser extension for Chrome and Chromium browsers.",
    platform: "web",
    layers: {
      language: ["typescript", "javascript"],
      frontend: ["react"],
      bundler: ["vite"],
      testing: ["vitest", "playwright"],
      hosting: ["chrome-web-store"],
    },
    excludes: ["next", "nestjs", "ghost", "express", "fastify"],
    knowledgePacks: ["platforms/browser-extension-chrome", "frameworks/react", "disciplines/security"],
  },
  {
    id: "browser-extension-safari",
    name: "Safari Web Extension",
    description: "Safari Web Extension with Xcode wrapper and shared web assets.",
    platform: "web",
    layers: {
      language: ["typescript", "javascript", "swift"],
      frontend: ["react"],
      bundler: ["vite"],
      testing: ["vitest"],
      hosting: ["mac-app-store"],
    },
    excludes: ["next", "nestjs", "ghost", "express", "fastify"],
    knowledgePacks: [
      "platforms/browser-extension-safari",
      "platforms/browser-extension-chrome",
      "disciplines/security",
    ],
  },
  {
    id: "gpt-app",
    name: "GPT App / Actions",
    description: "Custom GPT, GPT Actions, or OpenAI Apps SDK integration with HTTPS API backend.",
    platform: "web",
    layers: {
      language: ["typescript", "javascript"],
      frontend: ["react"],
      bundler: ["vite", "next"],
      backend: ["express", "fastify", "next"],
      testing: ["vitest", "jest"],
      database: ["postgresql", "sqlite"],
      hosting: ["vercel", "azure", "aws"],
    },
    excludes: ["ghost", "react-native", "electron"],
    knowledgePacks: ["platforms/gpt-apps", "disciplines/security"],
    runtimeAdapters: ["express", "fastify", "next"],
  },
  {
    id: "mcp-server",
    name: "MCP Server",
    description: "Model Context Protocol server for AI clients (Cursor, Claude, ChatGPT).",
    platform: "web",
    layers: {
      language: ["typescript", "javascript"],
      backend: ["express", "fastify"],
      testing: ["vitest", "jest"],
      hosting: ["vercel", "railway", "docker"],
    },
    excludes: ["ghost", "react-native", "electron", "next"],
    knowledgePacks: ["platforms/mcp-server", "disciplines/security"],
    runtimeAdapters: ["express", "fastify"],
  },
  {
    id: "flutter-mobile",
    name: "Flutter Mobile",
    description: "Cross-platform iOS and Android app with Flutter and Dart.",
    platform: "mobile",
    layers: {
      language: ["dart"],
      frontend: ["flutter"],
      bundler: ["flutter"],
      backend: ["express", "fastify", "supabase"],
      testing: ["flutter-test"],
      database: ["postgresql", "sqlite", "supabase"],
      hosting: ["play-store", "app-store"],
    },
    excludes: ["react", "react-native", "next", "vite", "ghost", "vue", "svelte"],
    knowledgePacks: ["frameworks/flutter", "disciplines/mobile-development", "disciplines/security"],
  },
  {
    id: "ios-native",
    name: "iOS Native (Swift)",
    description: "Native iPhone and iPad app with SwiftUI.",
    platform: "mobile",
    layers: {
      language: ["swift"],
      frontend: ["swiftui"],
      testing: ["xctest"],
      database: ["sqlite", "postgresql"],
      hosting: ["app-store"],
    },
    excludes: ["react", "react-native", "flutter", "next", "vite", "ghost"],
    knowledgePacks: ["platforms/ios-swift", "disciplines/mobile-development", "disciplines/security"],
  },
  {
    id: "android-native",
    name: "Android Native (Kotlin)",
    description: "Native Android app with Jetpack Compose.",
    platform: "mobile",
    layers: {
      language: ["kotlin"],
      frontend: ["compose"],
      testing: ["junit"],
      database: ["sqlite", "postgresql"],
      hosting: ["play-store"],
    },
    excludes: ["react", "react-native", "flutter", "next", "vite", "ghost"],
    knowledgePacks: ["platforms/android-kotlin", "disciplines/mobile-development", "disciplines/security"],
  },
  {
    id: "astro-static",
    name: "Astro Marketing Site",
    description: "Static marketing site, docs, or blog with Astro.",
    platform: "web",
    layers: {
      language: ["typescript", "javascript"],
      frontend: ["astro"],
      bundler: ["astro"],
      testing: ["vitest", "playwright"],
      hosting: ["vercel", "netlify", "cloudflare"],
    },
    excludes: ["next", "express", "fastify", "nestjs", "ghost", "react-native"],
    knowledgePacks: ["frameworks/astro", "platforms/marketing-website", "disciplines/security"],
  },
  {
    id: "wordpress-headless",
    name: "WordPress Headless",
    description: "WordPress as CMS with separate Next.js, Astro, or React frontend.",
    platform: "cms",
    layers: {
      language: ["typescript", "javascript", "php"],
      frontend: ["next", "react", "astro"],
      bundler: ["next", "vite", "astro"],
      backend: ["wordpress"],
      database: ["mysql", "postgresql"],
      hosting: ["vercel", "wp-engine", "kinsta"],
    },
    excludes: ["ghost", "nestjs"],
    knowledgePacks: ["platforms/wordpress-headless", "cms/wordpress", "languages/php", "disciplines/security"],
  },
  {
    id: "sanity-headless",
    name: "Sanity Headless",
    description: "Sanity structured content with Next.js, Remix, or Astro frontend.",
    platform: "cms",
    layers: {
      language: ["typescript", "javascript"],
      frontend: ["next", "react", "astro"],
      bundler: ["next", "vite", "astro"],
      backend: ["sanity"],
      database: ["sanity"],
      hosting: ["vercel", "netlify"],
    },
    excludes: ["ghost", "wordpress", "strapi"],
    knowledgePacks: ["cms/sanity", "frameworks/react", "disciplines/security"],
  },
  {
    id: "strapi-headless",
    name: "Strapi Headless",
    description: "Self-hosted Strapi CMS with separate frontend.",
    platform: "cms",
    layers: {
      language: ["typescript", "javascript"],
      frontend: ["next", "react", "vue", "astro"],
      bundler: ["next", "vite", "astro"],
      backend: ["strapi"],
      database: ["postgresql", "mysql", "sqlite"],
      hosting: ["vercel", "railway", "azure"],
    },
    excludes: ["ghost", "wordpress", "sanity"],
    knowledgePacks: ["cms/strapi", "disciplines/security"],
  },
  {
    id: "payload-cms",
    name: "Payload CMS + Next.js",
    description: "Code-first Payload CMS embedded in Next.js monorepo.",
    platform: "cms",
    layers: {
      language: ["typescript"],
      frontend: ["next", "react"],
      bundler: ["next"],
      backend: ["next", "payload"],
      database: ["postgresql", "mongodb"],
      hosting: ["vercel", "railway"],
    },
    excludes: ["ghost", "wordpress", "vite", "express"],
    knowledgePacks: ["cms/payload", "frameworks/nextjs", "frameworks/react", "disciplines/security"],
    runtimeAdapters: ["next"],
  },
  {
    id: "contentful-headless",
    name: "Contentful Headless",
    description: "Contentful SaaS CMS with enterprise frontend.",
    platform: "cms",
    layers: {
      language: ["typescript", "javascript"],
      frontend: ["next", "react"],
      bundler: ["next", "vite"],
      hosting: ["vercel"],
    },
    excludes: ["ghost", "wordpress"],
    knowledgePacks: ["cms/contentful", "disciplines/security"],
  },
  {
    id: "remix-fullstack",
    name: "Remix Full-Stack",
    description: "Remix with loaders, actions, and progressive enhancement.",
    platform: "web",
    layers: {
      language: ["typescript", "javascript"],
      frontend: ["react"],
      bundler: ["remix"],
      backend: ["remix"],
      testing: ["vitest", "playwright"],
      database: ["postgresql", "sqlite"],
      hosting: ["vercel", "fly", "railway"],
    },
    excludes: ["next", "vite", "vue", "svelte", "ghost"],
    knowledgePacks: ["frameworks/remix", "frameworks/react", "disciplines/security"],
    runtimeAdapters: ["remix"],
  },
  {
    id: "nuxt-fullstack",
    name: "Nuxt Full-Stack",
    description: "Nuxt 3 with Vue, Nitro server, and SSR.",
    platform: "web",
    layers: {
      language: ["typescript", "javascript"],
      frontend: ["vue"],
      bundler: ["nuxt"],
      backend: ["nuxt"],
      testing: ["vitest", "playwright"],
      hosting: ["vercel", "netlify", "node"],
    },
    excludes: ["next", "react", "svelte", "ghost"],
    knowledgePacks: ["frameworks/nuxt", "frameworks/vue", "disciplines/security"],
  },
  {
    id: "sveltekit-fullstack",
    name: "SvelteKit Full-Stack",
    description: "SvelteKit with SSR, adapters, and form actions.",
    platform: "web",
    layers: {
      language: ["typescript", "javascript"],
      frontend: ["svelte"],
      bundler: ["sveltekit"],
      backend: ["sveltekit"],
      testing: ["vitest", "playwright"],
      hosting: ["vercel", "netlify", "node"],
    },
    excludes: ["next", "react", "vue", "ghost"],
    knowledgePacks: ["frameworks/sveltekit", "frameworks/svelte", "disciplines/security"],
  },
  {
    id: "angular-spa",
    name: "Angular SPA",
    description: "Angular enterprise single-page application.",
    platform: "web",
    layers: {
      language: ["typescript"],
      frontend: ["angular"],
      bundler: ["angular"],
      backend: ["express", "nestjs"],
      testing: ["jest", "playwright"],
      hosting: ["azure", "aws"],
    },
    excludes: ["next", "react", "vue", "svelte", "ghost"],
    knowledgePacks: ["frameworks/angular", "languages/typescript", "disciplines/security"],
  },
  {
    id: "hono-api",
    name: "Hono Edge API",
    description: "Hono API on Workers, Bun, or Node edge.",
    platform: "web",
    layers: {
      language: ["typescript", "javascript"],
      backend: ["hono"],
      testing: ["vitest"],
      hosting: ["cloudflare", "vercel", "bun"],
    },
    excludes: ["next", "nestjs", "express", "ghost"],
    knowledgePacks: ["frameworks/hono", "disciplines/edge-computing", "disciplines/security"],
    runtimeAdapters: ["hono"],
  },
  {
    id: "django-fullstack",
    name: "Django",
    description: "Django web with optional DRF API and admin.",
    platform: "web",
    layers: {
      language: ["python"],
      backend: ["django"],
      testing: ["pytest"],
      database: ["postgresql", "mysql", "sqlite"],
      hosting: ["railway", "aws", "azure"],
    },
    excludes: ["next", "react", "ghost"],
    knowledgePacks: ["frameworks/django", "languages/python", "disciplines/security"],
  },
  {
    id: "fastapi-api",
    name: "FastAPI",
    description: "Python async API with Pydantic and OpenAPI.",
    platform: "web",
    layers: {
      language: ["python"],
      backend: ["fastapi"],
      testing: ["pytest"],
      database: ["postgresql", "sqlite"],
      hosting: ["railway", "aws", "azure"],
    },
    excludes: ["django", "ghost"],
    knowledgePacks: ["frameworks/fastapi", "languages/python", "disciplines/api-design", "disciplines/security"],
  },
  {
    id: "laravel-fullstack",
    name: "Laravel",
    description: "Laravel PHP full-stack or API with Inertia/Livewire.",
    platform: "web",
    layers: {
      language: ["php"],
      frontend: ["vue", "react"],
      backend: ["laravel"],
      database: ["mysql", "postgresql"],
      hosting: ["laravel-forge", "aws"],
    },
    excludes: ["next", "ghost", "django"],
    knowledgePacks: ["frameworks/laravel", "languages/php", "disciplines/security"],
  },
  {
    id: "healthcare-fhir",
    name: "Healthcare FHIR API",
    description: "HIPAA-aligned clinical app with FHIR R4 and SMART on FHIR — integrate via Redox or direct EHR.",
    platform: "web",
    layers: {
      language: ["typescript", "python"],
      frontend: ["react", "next"],
      bundler: ["vite", "next"],
      backend: ["fastapi", "nestjs", "express", "next"],
      database: ["postgresql"],
      testing: ["vitest", "pytest", "playwright"],
      hosting: ["azure", "aws", "hipaa-eligible"],
    },
    excludes: ["ghost", "wordpress"],
    knowledgePacks: [
      "healthcare/overview",
      "healthcare/fhir-r4",
      "healthcare/smart-on-fhir",
      "healthcare/phi-engineering",
      "healthcare/redox",
      "compliance/tiered-standards",
      "disciplines/security",
    ],
    runtimeAdapters: ["express", "fastify", "next"],
  },
  {
    id: "gaming-unity",
    name: "Unity Game",
    description: "Cross-platform game with Unity — multiplayer, Steam, or mobile distribution.",
    platform: "desktop",
    layers: {
      language: ["csharp"],
      frontend: ["unity"],
      backend: ["nodejs", "csharp"],
      database: ["postgresql", "redis"],
      hosting: ["aws", "playfab"],
    },
    excludes: ["next", "wordpress", "ghost"],
    knowledgePacks: [
      "gaming/unity",
      "gaming/multiplayer-authoritative",
      "gaming/anti-cheat",
      "languages/csharp",
      "disciplines/security",
    ],
  },
  {
    id: "erp-sap-integration",
    name: "SAP Integration",
    description: "Enterprise app integrating with SAP S/4HANA via OData, CPI, or iPaaS.",
    platform: "web",
    layers: {
      language: ["java", "typescript"],
      backend: ["spring", "nestjs"],
      database: ["postgresql", "sql-server"],
      hosting: ["azure", "aws"],
    },
    excludes: ["ghost", "wordpress"],
    knowledgePacks: [
      "erp/sap",
      "integrations/workato",
      "integrations/mulesoft",
      "disciplines/security",
      "compliance/soc2",
    ],
  },
  {
    id: "fintech-plaid",
    name: "Fintech (Plaid)",
    description: "Bank linking, KYC, and payments — Plaid, Stripe, compliance-first.",
    platform: "web",
    layers: {
      language: ["typescript"],
      frontend: ["react", "next"],
      backend: ["nestjs", "express", "next"],
      database: ["postgresql"],
      hosting: ["aws", "vercel"],
    },
    excludes: ["ghost", "wordpress"],
    knowledgePacks: [
      "payments/plaid",
      "payments/onfido",
      "payments/overview",
      "compliance/tiered-standards",
      "disciplines/security",
    ],
    runtimeAdapters: ["express", "fastify", "next"],
  },
  {
    id: "ecommerce-shopify",
    name: "Shopify Headless",
    description: "Headless commerce with Shopify Storefront API or Hydrogen.",
    platform: "web",
    layers: {
      language: ["typescript"],
      frontend: ["react", "next"],
      bundler: ["vite", "next"],
      database: ["postgresql"],
      hosting: ["vercel", "shopify-oxygen"],
    },
    excludes: ["wordpress", "ghost"],
    knowledgePacks: [
      "ecommerce/shopify",
      "ecommerce/shopify-hydrogen",
      "payments/stripe",
      "disciplines/security",
    ],
    runtimeAdapters: ["next"],
  },
  {
    id: "ai-llm-saas",
    name: "AI / LLM Product",
    description: "RAG, chat, evals — Vercel AI SDK with guardrails and observability.",
    platform: "web",
    layers: {
      language: ["typescript", "python"],
      frontend: ["react", "next"],
      backend: ["next", "fastapi"],
      database: ["postgresql", "pinecone"],
      hosting: ["vercel", "aws"],
    },
    excludes: ["ghost"],
    knowledgePacks: [
      "ai/vercel-ai-sdk",
      "ai/rag-patterns",
      "ai/ai-evals",
      "ai/prompt-injection-defense",
      "ai/openai",
      "disciplines/security",
    ],
    runtimeAdapters: ["next", "express"],
  },
  {
    id: "edtech-lms",
    name: "EdTech LMS",
    description: "LMS integration — LTI 1.3, Canvas/Moodle, FERPA-aware.",
    platform: "web",
    layers: {
      language: ["typescript"],
      frontend: ["react", "next"],
      backend: ["nestjs", "express"],
      database: ["postgresql"],
      hosting: ["aws", "azure"],
    },
    excludes: ["ghost"],
    knowledgePacks: [
      "edtech/lti",
      "edtech/canvas",
      "compliance/ferpa",
      "disciplines/security",
    ],
  },
  {
    id: "iot-mqtt",
    name: "IoT MQTT Platform",
    description: "Device telemetry and commands over MQTT with cloud bridge.",
    platform: "web",
    layers: {
      language: ["typescript", "python"],
      backend: ["nestjs", "fastapi"],
      database: ["postgresql", "timescaledb"],
      hosting: ["aws", "azure"],
    },
    excludes: ["ghost", "wordpress"],
    knowledgePacks: ["iot/mqtt", "iot/aws-iot-core", "databases/timescaledb", "disciplines/security"],
  },
  {
    id: "insurance-insurtech",
    name: "Insurance Insurtech",
    description: "Policy and claims integration — Guidewire, Duck Creek patterns.",
    platform: "web",
    layers: {
      language: ["java", "typescript"],
      backend: ["spring", "nestjs"],
      database: ["postgresql", "sql-server"],
      hosting: ["aws", "azure"],
    },
    excludes: ["ghost"],
    knowledgePacks: [
      "insurance/guidewire",
      "insurance/claims-automation",
      "compliance/soc2",
      "disciplines/security",
    ],
  },
  {
    id: "observability-production",
    name: "Production Observability",
    description: "Datadog/Sentry/OpenTelemetry — SLOs, incidents, and CI quality gates.",
    platform: "web",
    layers: {
      language: ["typescript"],
      backend: ["nestjs", "express", "next"],
      hosting: ["aws", "vercel", "kubernetes"],
    },
    excludes: ["ghost"],
    knowledgePacks: [
      "observability/datadog",
      "observability/sentry",
      "observability/opentelemetry",
      "observability/grafana-stack",
      "disciplines/sli-slo",
    ],
  },
  {
    id: "cloud-aws-saas",
    name: "AWS SaaS",
    description: "AWS-native SaaS — ECS/Lambda, RDS, Cognito, CloudFront.",
    platform: "web",
    layers: {
      language: ["typescript"],
      frontend: ["react", "next"],
      backend: ["nestjs", "express"],
      database: ["postgresql", "dynamodb"],
      hosting: ["aws"],
    },
    excludes: ["ghost"],
    knowledgePacks: [
      "cloud/aws-overview",
      "cloud/aws-rds",
      "cloud/aws-lambda",
      "cloud/aws-cognito",
      "cloud/aws-cloudfront",
      "cloud/aws-dr-playbook",
      "disciplines/security",
    ],
    runtimeAdapters: ["express", "fastify"],
  },
];

/** Hard conflicts — if all listed technologies are detected, flag it */
export const STACK_CONFLICTS: StackConflict[] = [
  {
    technologies: ["next", "vite"],
    reason: "Next.js includes its own bundler (Turbopack/Webpack). Do not add Vite.",
    severity: "error",
  },
  {
    technologies: ["ghost", "react"],
    reason: "Ghost is a standalone CMS. Use ghost-cms archetype or headless CMS pattern — not React SPA in same app.",
    severity: "error",
  },
  {
    technologies: ["ghost", "vite"],
    reason: "Ghost manages its own frontend. Vite does not belong in a Ghost project.",
    severity: "error",
  },
  {
    technologies: ["react", "vue"],
    reason: "Use one UI framework per frontend. Pick react-vite-api or vue-vite-api.",
    severity: "error",
  },
  {
    technologies: ["react", "svelte"],
    reason: "Use one UI framework per frontend.",
    severity: "error",
  },
  {
    technologies: ["vue", "svelte"],
    reason: "Use one UI framework per frontend.",
    severity: "error",
  },
  {
    technologies: ["express", "fastify"],
    reason: "Multiple Node HTTP frameworks detected. Use one primary API server per service.",
    severity: "warning",
  },
  {
    technologies: ["express", "nestjs"],
    reason: "Express and NestJS are both present — use nestjs-modular or react-vite-api, not both as primary APIs.",
    severity: "error",
  },
  {
    technologies: ["fastify", "nestjs"],
    reason: "Fastify and NestJS are both present — pick one backend framework.",
    severity: "error",
  },
  {
    technologies: ["next", "express"],
    reason:
      "Next.js with a separate Express server is usually wrong — use route handlers or change archetype to react-vite-api.",
    severity: "warning",
  },
  {
    technologies: ["electron", "tauri"],
    reason: "Electron and Tauri are both desktop shells — pick desktop-electron or desktop-tauri, not both.",
    severity: "error",
  },
];

export function getArchetype(id: string): StackArchetype | undefined {
  return STACK_ARCHETYPES.find((a) => a.id === id);
}

export function formatStackCatalog(): string {
  const lines = [
    "DNA Stack Archetypes",
    "====================",
    "",
    "Approved system shapes — pick one per project. AI must not mix excluded technologies.",
    "",
  ];

  for (const a of STACK_ARCHETYPES) {
    lines.push(`• ${a.id}`);
    lines.push(`  ${a.name} — ${a.description}`);
    lines.push(`  Platform: ${a.platform}`);
  }

  lines.push("", "Commands:", "  dna stack list", "  dna stack recommend", "  dna validate  (checks stack conflicts)", "");
  return lines.join("\n");
}
