import { def, packsFromDefs } from "./bundled-catalog-pack-factory.js";

const D = (
  id: string,
  name: string,
  desc: string,
  when: string,
  how: string,
  tags?: string[],
) => def(id, name, desc, when, how, tags ?? ["databases"]);

export const DATABASE_PACK_DEFS = [
  D("databases/postgresql", "PostgreSQL", "Advanced open-source relational database", "Default OLTP for DNA SaaS. JSONB, extensions, logical replication.", "Use managed RDS/Neon/Supabase. Migrations via Prisma/Drizzle/Flyway. PITR backups. Read replicas for scale."),
  D("databases/mysql", "MySQL / MariaDB", "Widely deployed relational database", "WordPress, legacy LAMP, some enterprises.", "InnoDB, utf8mb4. Avoid MyISAM. Replication lag monitoring."),
  D("databases/sql-server", "SQL Server", "Microsoft relational database", "Enterprise .NET, healthcare on-prem.", "Azure SQL or self-hosted. TDE at rest. Entra auth."),
  D("databases/oracle", "Oracle Database", "Enterprise RDBMS", "Large enterprise ERP adjacent systems.", "Prefer avoid for greenfield. Licensing complexity."),
  D("databases/mongodb", "MongoDB", "Document database", "Flexible schema, content catalogs, event stores.", "Define schema in app layer. Transactions for multi-doc. Atlas for managed."),
  D("databases/redis", "Redis", "In-memory cache, pub/sub, streams", "Sessions, rate limits, leaderboards, job queues.", "Never primary source of truth. TLS, AUTH, persistence AOF/RDB if needed."),
  D("databases/dynamodb", "DynamoDB", "AWS serverless key-value/document", "Serverless scale, predictable partition keys.", "Design access patterns first. On-demand vs provisioned. DAX for cache."),
  D("databases/neon", "Neon", "Serverless Postgres branching", "Dev branches, scale-to-zero Postgres.", "Branch per PR. Connection pooling. Data HQ region pin."),
  D("databases/planetscale", "PlanetScale", "Serverless MySQL with branching", "MySQL teams wanting branch deploys.", "Vitess underneath. Deploy requests for schema."),
  D("databases/turso", "Turso", "libSQL edge SQLite", "Edge replicas, embedded local-first.", "Primary + edge read replicas. libsql client."),
  D("databases/cockroachdb", "CockroachDB", "Distributed SQL", "Multi-region SQL with survivability.", "SERIALIZABLE default. Region survival goals."),
  D("databases/cassandra", "Apache Cassandra", "Wide-column distributed store", "High write throughput, time-series at scale.", "Query-driven modeling. Tunable consistency."),
  D("databases/clickhouse", "ClickHouse", "Columnar OLAP", "Analytics, event telemetry, funnels.", "MergeTree engines. Batch inserts. Separate from OLTP."),
  D("databases/duckdb", "DuckDB", "Embedded OLAP", "Local analytics, data science, edge BI.", "Parquet in object storage. Not multi-user OLTP."),
  D("databases/bigquery", "Google BigQuery", "Serverless data warehouse", "Petabyte analytics, ML on warehouse.", "Partitioning, clustering. Cost controls on full table scan."),
  D("databases/snowflake", "Snowflake", "Cloud data warehouse", "Enterprise analytics, data sharing.", "Virtual warehouses. RBAC + masking policies."),
  D("databases/databricks", "Databricks", "Lakehouse platform", "Spark, ML, Delta Lake.", "Unity Catalog for governance. Jobs orchestration."),
  D("databases/elasticsearch", "Elasticsearch", "Search and log analytics", "Full-text search, ELK logs.", "Index lifecycle management. Avoid giant clusters as primary DB."),
  D("databases/opensearch", "OpenSearch", "OSS search fork", "AWS OpenSearch Service, self-hosted search.", "Same patterns as Elasticsearch licensing-wise."),
  D("databases/algolia", "Algolia", "Hosted search API", "Instant search UX for SaaS/marketing.", "Index via API. Secured API keys per tenant."),
  D("databases/meilisearch", "Meilisearch", "OSS hosted search", "Self-hosted Algolia alternative.", "Typo tolerance. Tenant tokens."),
  D("databases/typesense", "Typesense", "OSS search engine", "Fast typo-tolerant search.", "Collection schemas. HA raft cluster."),
  D("databases/pinecone", "Pinecone", "Vector database", "AI embeddings at scale.", "Namespaces per tenant. Metadata filters."),
  D("databases/weaviate", "Weaviate", "Vector + hybrid search", "RAG with semantic + keyword.", "Schema classes. GraphQL API."),
  D("databases/qdrant", "Qdrant", "Vector search engine", "Self-hosted/cloud vectors.", "Collections, HNSW indexes. Payload filtering."),
  D("databases/chroma", "Chroma", "Embedded vector DB", "Prototyping RAG, local dev.", "Upgrade to managed for production scale."),
  D("databases/pgvector", "pgvector", "Vectors in PostgreSQL", "RAG without separate vector DB.", "IVFFlat/HNSW indexes. Vacuum tuning."),
  D("databases/kafka", "Apache Kafka", "Event streaming platform", "Event sourcing, log aggregation, stream processing.", "Topic retention, idempotent producers, consumer groups."),
  D("databases/redpanda", "Redpanda", "Kafka-compatible streaming", "Lower ops than Kafka.", "Kafka API compatible clients."),
  D("databases/pulsar", "Apache Pulsar", "Multi-tenant messaging", "Geo-replication built-in.", "BookKeeper storage. Namespace isolation."),
  D("databases/rabbitmq", "RabbitMQ", "Message broker", "Task queues, classic AMQP.", "Durable queues. Dead-letter exchanges."),
  D("databases/aws-sqs-sns", "AWS SQS & SNS", "Managed queues and pub/sub", "Serverless decoupling on AWS.", "Visibility timeout, DLQ, FIFO when ordering needed."),
  D("databases/nats", "NATS", "Lightweight messaging", "Microservices, edge messaging.", "JetStream for persistence."),
  D("databases/neo4j", "Neo4j", "Graph database", "Relationship-heavy domains, fraud, knowledge graphs.", "Cypher queries. Graph Data Science for ML."),
  D("databases/influxdb", "InfluxDB", "Time-series database", "Metrics, IoT telemetry.", "Retention policies. Downsampling."),
  D("databases/timescaledb", "TimescaleDB", "Postgres time-series extension", "Metrics on Postgres skills.", "Hypertables. Continuous aggregates."),
  D("databases/firestore", "Cloud Firestore", "Firebase document DB", "Mobile/web realtime sync.", "Security rules. Subcollections per tenant."),
  D("databases/firebase-rtdb", "Firebase Realtime DB", "JSON realtime tree", "Legacy Firebase realtime.", "Prefer Firestore for new apps."),
  D("databases/prisma", "Prisma ORM", "TypeScript ORM and migrations", "DNA default ORM for Node.", "Schema in prisma file. Migrate deploy in CI."),
  D("databases/drizzle", "Drizzle ORM", "Lightweight SQL ORM", "SQL-first TypeScript teams.", "Schema as code. drizzle-kit push/migrate."),
  D("databases/dbt", "dbt", "Analytics transform layer", "Warehouse modeling SQL.", "Tests on models. Docs generation."),
  D("databases/airbyte", "Airbyte", "ELT connectors", "Sync operational DB to warehouse.", "Connection per source. PII masking in streams."),
  D("databases/airflow", "Apache Airflow", "Workflow orchestration", "Batch pipelines, data engineering.", "DAGs in code. Secrets backend."),
  D("databases/debezium", "Debezium", "Change data capture", "CDC to Kafka from Postgres/MySQL.", "Logical decoding slots. Monitor lag."),
  D("databases/convex", "Convex", "Reactive backend", "Realtime sync TypeScript backend.", "Functions + database unified. Vendor eval for HIPAA."),
  D("databases/instantdb", "InstantDB", "Realtime client-first DB", "Collaborative apps quickly.", "Permissions rules. Emerging — evaluate production needs."),
  D("databases/pocketbase", "PocketBase", "Embedded backend", "Small apps, admin UI included.", "Go single binary. SQLite based."),
  D("databases/appwrite", "Appwrite", "Open-source BaaS", "Self-hosted Firebase alternative.", "Docker deploy. Auth + storage + DB."),
];

export const DATABASE_PACKS = packsFromDefs(DATABASE_PACK_DEFS);
