/**
 * Additional software-industry verticals — startups → agencies → SME → enterprise.
 * Appended to INDUSTRY_SECTOR_DEFINITIONS via sector-definitions.ts
 */
import type { IndustrySectorDef } from "../industry/types.js";

function sector(
  id: string,
  name: string,
  description: string,
  extras: Omit<IndustrySectorDef, "id" | "name" | "description">,
): IndustrySectorDef {
  return { id, name, description, ...extras };
}

export const SOFTWARE_VERTICAL_SECTORS: IndustrySectorDef[] = [
  sector("cybersecurity", "Cybersecurity", "Security products, SOC tooling, identity, and vuln management", {
    landscape: `Vendors sell SIEM, EDR, IAM, ASPM, and security awareness to enterprises under constant threat pressure.`,
    influencers: `**Vendors:** CrowdStrike, Okta, Palo Alto, Wiz, Snyk\n**Standards:** NIST CSF, ISO 27001, CIS Controls`,
    techStack: `**Stacks:** Go/Rust agents, stream processing, threat intel feeds\n**Related:** \`security/*\`, \`compliance/soc2\`, \`auth/*\``,
    latest: `ASPM, AI-assisted triage, passwordless, zero-trust network access.`,
    practices: `**Do:** assume breach; least privilege; evidence-backed controls\n**Don't:** security theatre checklists without detection`,
    regulation: `SOC 2, ISO 27001, sector overlays (HIPAA/PCI) when selling into regulated buyers`,
    agencyNotes: `RFP-heavy; proof via pen-test and architecture diagrams wins deals`,
    uiPatterns: `Alert density with ack workflows; severity + text labels; dark ops themes common`,
    linkedPacks: ["compliance/soc2", "disciplines/security"],
    tags: ["cyber", "security"],
  }),
  sector("climate-tech", "Climate Tech", "Carbon, energy transition, ESG measurement, and climate risk software", {
    landscape: `Startups and enterprises measure emissions, optimize energy, and report ESG.`,
    influencers: `**Standards:** GHG Protocol, SBTi, CSRD\n**Players:** Watershed, Persefoni, utility innovators`,
    techStack: `Time-series, GIS, supplier data pipelines, audit trails`,
    latest: `CSRD reporting automation; AI for Scope 3 estimation with disclosure of uncertainty`,
    practices: `**Do:** provenance on emission factors\n**Don't:** greenwash unverifiable offsets`,
    regulation: `CSRD, SEC climate rules (region-dependent), advertising standards`,
    agencyNotes: `Clients need audit-ready exports; methodology docs matter as much as UI`,
    uiPatterns: `Dashboards with methodology footnotes; uncertainty ranges`,
    linkedPacks: ["industries/energy-utilities"],
    tags: ["climate", "esg"],
  }),
  sector("agritech", "AgriTech", "Farm ops, precision agriculture, supply chain for food producers", {
    landscape: `Hardware+software for yield, irrigation, livestock, and farm marketplaces.`,
    influencers: `John Deere ops platforms, climate corp, regional co-ops`,
    techStack: `IoT, offline-first mobile, geospatial, satellite imagery`,
    latest: `Edge inference in fields; carbon farming MRV`,
    practices: `**Do:** offline sync; rugged device UX\n**Don't:** assume always-on connectivity`,
    regulation: `Food safety, chemical usage logs, regional farm data rules`,
    agencyNotes: `Seasonal urgency; train field users in short sessions`,
    uiPatterns: `Large tap targets; map-centric; weather overlays`,
    linkedPacks: ["iot/mqtt", "maps/mapbox"],
    tags: ["agritech"],
  }),
  sector("aerospace-defense", "Aerospace & Defense", "Avionics-adjacent software, defense digital, dual-use platforms", {
    landscape: `High assurance, long procurement, air-gapped and classified constraints.`,
    influencers: `Prime contractors, NATO standards, national defense digital units`,
    techStack: `Strict SDLC, SBOMs, air-gap deploy, formal review gates`,
    latest: `Software-defined platforms; continuous ATO experiments`,
    practices: `**Do:** traceability from requirement → test\n**Don't:** cloud-default assumptions`,
    regulation: `ITAR/EAR, national security classifications, FedRAMP-like baselines`,
    agencyNotes: `Clearances and export controls dominate staffing`,
    uiPatterns: `Dense operational UIs; accessibility still required for operators`,
    linkedPacks: ["compliance/soc2", "disciplines/security"],
    tags: ["aerospace", "defense"],
  }),
  sector("automotive-mobility", "Automotive & Mobility", "Connected vehicles, EV charging, fleet, and mobility marketplaces", {
    landscape: `OEMs, Tier-1s, and mobility startups ship vehicle software and rider/driver apps.`,
    influencers: `Android Automotive, OEM clouds, ChargePoint-like networks`,
    techStack: `OTA pipelines, MQTT/CAN bridges, maps, realtime`,
    latest: `SDV architectures; battery health analytics; roaming charge networks`,
    practices: `**Do:** safety cases for driving-related features\n**Don't:** treat cars like mobile phones for update risk`,
    regulation: `UNECE WP.29, regional type approval, privacy for location`,
    agencyNotes: `Hardware schedules slip; plan software feature flags`,
    uiPatterns: `Driver distraction limits; high contrast; voice`,
    linkedPacks: ["iot/mqtt", "maps/mapbox"],
    tags: ["automotive", "mobility"],
  }),
  sector("telecom", "Telecom & Connectivity", "BSS/OSS adjacent apps, MVNO, network automation portals", {
    landscape: `Operators and MVNEs need billing, provisioning, and network observability UIs.`,
    influencers: `TM Forum, major telcos, cloud network vendors`,
    techStack: `Event-driven provisioning, rating engines, SNMP/telemetry`,
    latest: `5G network slicing portals; AI NOC copilots`,
    practices: `**Do:** idempotent provisioning\n**Don't:** chatty synchronous cascades across BSS`,
    regulation: `Lawful intercept hooks (careful), consumer telecom rules, net neutrality variants`,
    agencyNotes: `Legacy BSS integrations dominate estimates`,
    uiPatterns: `Ops consoles; customer self-care with bill clarity`,
    linkedPacks: ["disciplines/platform-engineering"],
    tags: ["telecom"],
  }),
  sector("crypto-web3", "Crypto & Web3", "Wallets, exchanges, on-chain apps, and custody platforms", {
    landscape: `High-risk financial UX with irreversible transactions and phishing pressure.`,
    influencers: `Ethereum ecosystem, major CEXs/DEXs, wallet vendors`,
    techStack: `Indexers, HSM/custody, chain RPCs, simulation before sign`,
    latest: `Account abstraction; intent-based UX; stricter travel-rule compliance`,
    practices: `**Do:** simulate tx; clear human-readable signing\n**Don't:** bury approvals`,
    regulation: `MiCA, travel rule, MSB/VASP licensing by region`,
    agencyNotes: `Security audit budget non-negotiable`,
    uiPatterns: `Transaction previews; risk banners; hardware wallet flows`,
    linkedPacks: ["compliance/soc2", "payments/stripe"],
    tags: ["web3", "crypto"],
  }),
  sector("hr-tech", "HR Tech", "HRIS, payroll-adjacent, recruiting, and people analytics", {
    landscape: `Employers buy ATS, HRIS, performance, and workforce planning tools.`,
    influencers: `Workday, Greenhouse, Rippling, regional payroll providers`,
    techStack: `RBAC, audit logs, payroll exports, SSO`,
    latest: `AI screening with bias controls; skills graphs`,
    practices: `**Do:** explainability for hiring AI\n**Don't:** silent automated rejection without policy`,
    regulation: `Employment law, GDPR employee data, EEO reporting`,
    agencyNotes: `Payroll mistakes are existential — test fixtures carefully`,
    uiPatterns: `Dense admin tables; employee self-service clarity`,
    linkedPacks: ["compliance/gdpr", "auth/clerk"],
    tags: ["hrtech"],
  }),
  sector("martech", "MarTech & AdTech", "CDPs, campaign tools, attribution, and ad platforms", {
    landscape: `Marketers need orchestration, consent, and measurement across channels.`,
    influencers: `Segment, Braze, Google/Meta ads ecosystems`,
    techStack: `Event pipelines, identity resolution, consent stores`,
    latest: `Cookieless measurement; first-party data clean rooms`,
    practices: `**Do:** consent before activation\n**Don't:** dark patterns on unsubscribe`,
    regulation: `GDPR/ePrivacy, TCPA, platform ad policies`,
    agencyNotes: `Attribution debates — be honest about model limits`,
    uiPatterns: `Journey builders; audience size previews; audit of who got messaged`,
    linkedPacks: ["compliance/gdpr", "integrations/posthog"],
    tags: ["martech", "adtech"],
  }),
  sector("biotech", "Biotech & Life Sciences", "Lab software, clinical trial ops, and research platforms", {
    landscape: `Labs and biotech firms need LIMS-like workflows, sample tracking, and collaboration.`,
    influencers: `Benchling-like platforms, CRO tooling, FDA digital guidance`,
    techStack: `Immutable audit, ELN patterns, instrument integrations`,
    latest: `AI for molecule design with human review gates`,
    practices: `**Do:** chain of custody\n**Don't:** overwrite raw instrument data`,
    regulation: `GxP, 21 CFR Part 11, clinical trial regulations`,
    agencyNotes: `Validation documentation is part of delivery`,
    uiPatterns: `Protocol-driven forms; versioned experiments`,
    linkedPacks: ["industries/healthcare", "compliance/hipaa"],
    tags: ["biotech", "life-sciences"],
  }),
  sector("construction-tech", "Construction Tech", "Jobsite software, BIM-adjacent collaboration, and contractor ops", {
    landscape: `GCs and subs coordinate RFIs, drawings, safety, and payments.`,
    influencers: `Procore-like platforms, Autodesk construction cloud`,
    techStack: `Offline mobile, document markup, geospatial site maps`,
    latest: `Reality capture + progress AI; embedded payments`,
    practices: `**Do:** offline-first; photo evidence trails\n**Don't:** assume desk workers only`,
    regulation: `OSHA-like safety, lien/payment laws by region`,
    agencyNotes: `Train on site; rugged device support`,
    uiPatterns: `Huge tap targets; markup tools; simple status`,
    linkedPacks: ["maps/mapbox"],
    tags: ["construction"],
  }),
  sector("sports-fitness", "Sports & Fitness Tech", "Training, fan engagement, wearables, and club ops software", {
    landscape: `Consumer fitness apps, team analytics, and venue experiences.`,
    influencers: `Whoop/Strava-like apps, league digital arms`,
    techStack: `Mobile, wearables SDKs, realtime scores`,
    latest: `AI coaching; privacy of biometric data`,
    practices: `**Do:** biometric minimization\n**Don't:** share health data casually`,
    regulation: `Health-adjacent privacy; sports betting regs if applicable`,
    agencyNotes: `Seasonal spikes; content + product intertwined`,
    uiPatterns: `Motivational UX; charts; social feeds carefully moderated`,
    linkedPacks: ["frameworks/react-native", "integrations/posthog"],
    tags: ["sports", "fitness"],
  }),
  sector("developer-tools", "Developer Tools", "Devtools, CI platforms, observability products, and API platforms", {
    landscape: `Developers are the buyers — DX is the product.`,
    influencers: `Vercel, GitHub, Datadog, Postman-like ecosystems`,
    techStack: `CLIs, SDKs, docs-as-product, usage-based billing`,
    latest: `AI pair agents; policy-as-code; OpenTelemetry everywhere`,
    practices: `**Do:** time-to-hello-world <5 minutes\n**Don't:** enterprise sales motion without self-serve`,
    regulation: `SOC 2 expected; data residency for enterprise`,
    agencyNotes: `Ship public changelogs; break glass for breaking API changes`,
    uiPatterns: `Docs-first; copy-paste snippets; dark mode`,
    linkedPacks: ["disciplines/platform-engineering", "disciplines/continuous-delivery"],
    tags: ["devtools", "dx"],
  }),
  sector("marketplace-platforms", "Marketplace Platforms", "Multi-sided marketplaces and platform businesses", {
    landscape: `Liquidity, trust & safety, and take-rate economics dominate roadmap.`,
    influencers: `Airbnb/Uber-like playbooks, Shopify ecosystem apps`,
    techStack: `Search, payments split, messaging, admin moderation`,
    latest: `AI moderation; embedded finance for sellers`,
    practices: `**Do:** model both sides; appeals paths\n**Don't:** growth-hack trust away`,
    regulation: `Platform liability variants, payments, consumer law`,
    agencyNotes: `Admin portal is a first-class product`,
    uiPatterns: `Dual UX (supply/demand); strong admin tables`,
    linkedPacks: ["companies/platform-marketplace", "payments/stripe"],
    tags: ["marketplace"],
  }),
  sector("nonprofit-civic", "Nonprofit & Civic Tech", "Mission-driven software, civic services, and donor platforms", {
    landscape: `Limited budgets, high accessibility needs, grant-driven roadmaps.`,
    influencers: `Code for America-like orgs, NGO digital teams`,
    techStack: `Simple stacks, CRM integrations, donations`,
    latest: `Open data; participatory budgeting tools`,
    practices: `**Do:** accessibility first; multilingual\n**Don't:** dark-pattern fundraising`,
    regulation: `Charity law, GDPR, public-sector procurement when civic`,
    agencyNotes: `Pro-bono scopes still need DoD and security basics`,
    uiPatterns: `Plain language; WCAG AA; low-bandwidth`,
    linkedPacks: ["companies/nonprofit", "compliance/wcag-22"],
    tags: ["nonprofit", "civic"],
  }),
  sector("gaming", "Gaming", "Games, liveops, and player platforms", {
    landscape: `Liveops calendars, platform certifications, and anti-cheat shape delivery.`,
    influencers: `Major publishers, Steam/console ecosystems, Unity/Unreal`,
    techStack: `Realtime, economies, analytics, content pipelines`,
    latest: `UGC moderation; AI NPCs with safety; cross-play`,
    practices: `**Do:** economy simulation before launch\n**Don't:** ship unpaid currency bugs`,
    regulation: `Platform policies, loot-box rules, COPPA/kids`,
    agencyNotes: `Content freezes before seasons; liveops is the product`,
    uiPatterns: `High stimulus consumer UX; clear purchase flows`,
    linkedPacks: ["methodologies/industry-gaming"],
    tags: ["gaming"],
  }),
  sector("manufacturing-software", "Manufacturing Software", "MES-adjacent, factory ops, and industrial SaaS", {
    landscape: `Uptime, traceability, and OT/IT boundaries dominate.`,
    influencers: `Siemens/Rockwell ecosystems, industrial IoT vendors`,
    techStack: `Time-series, edge gateways, digital twins`,
    latest: `Predictive maintenance; digital work instructions`,
    practices: `**Do:** OT isolation\n**Don't:** remote control without safety interlocks`,
    regulation: `Safety standards, export controls on some tech`,
    agencyNotes: `Plant downtime windows are sacred`,
    uiPatterns: `Floor-readable UI; alarm ack; multilingual workers`,
    linkedPacks: ["iot/mqtt", "methodologies/industry-manufacturing"],
    tags: ["manufacturing"],
  }),
  sector("insurtech", "InsurTech", "Insurance products, claims, and underwriting software", {
    landscape: `Carriers and MGAs digitize quotes, claims, and fraud detection.`,
    influencers: `Guidewire-adjacent ecosystems, modern MGAs`,
    techStack: `Rules engines, document OCR, audit trails`,
    latest: `Usage-based insurance; AI claims with human gates`,
    practices: `**Do:** explainability on declines\n**Don't:** silent model changes on pricing`,
    regulation: `Insurance licensing, unfair practices, data retention`,
    agencyNotes: `Actuarial and compliance stakeholders early`,
    uiPatterns: `Guided claims; status timelines; document upload`,
    linkedPacks: ["methodologies/industry-insurtech"],
    tags: ["insurtech"],
  }),
];
