import { join } from "node:path";
import { readFile } from "node:fs/promises";
import type { DnaConfig } from "@humaan/dna-config";
import { writeFileEnsured, writeJsonFile, fileExists } from "../fs.js";
import { loadDnaConfig } from "../validator.js";
import { installKnowledgePackById } from "../marketplace/install.js";
import { scanSurfaceInventory, formatInventorySummary, type SurfaceInventory } from "./inventory.js";

export interface RbacPlanOptions {
  root: string;
  /** Natural language requirement from the user */
  quote?: string;
  /** Comma-separated or array of role names */
  roles: string[];
  /** Default deny — no access unless explicitly granted */
  denyByDefault?: boolean;
  /** Feature or area being secured, e.g. "dashboard" */
  feature?: string;
  /** Zero-trust enforcement level */
  zeroTrust?: boolean;
}

export interface RbacPlanResult {
  planPath: string;
  matrixPath: string;
  matrixJsonPath: string;
  context: string;
  inventory: SurfaceInventory;
}

const STANDARD_ROLES_HELP = ["employee", "manager", "hr", "operations", "admin"];

function normalizeRoles(roles: string[]): string[] {
  const normalized = roles.map((r) => r.trim().toLowerCase()).filter(Boolean);
  return [...new Set(normalized)];
}

function buildPermissionMatrix(roles: string[], feature: string, inventory: SurfaceInventory) {
  const features = new Set<string>([feature]);

  for (const r of inventory.routes.slice(0, 20)) features.add(r.path);
  for (const p of inventory.pages.slice(0, 15)) features.add(p.path);
  for (const a of inventory.apis.slice(0, 15)) features.add(a.path);

  const matrix: Record<string, Record<string, boolean>> = {};
  for (const feat of features) {
    matrix[feat] = {};
    for (const role of roles) {
      matrix[feat][role] = role === "admin";
    }
  }
  return matrix;
}

function matrixMarkdown(matrix: Record<string, Record<string, boolean>>, roles: string[]): string {
  const features = Object.keys(matrix);
  const header = `| Feature / Surface | ${roles.join(" | ")} |`;
  const sep = `| --- | ${roles.map(() => "---").join(" | ")} |`;
  const rows = features.map((feat) => {
    const cells = roles.map((r) => (matrix[feat]?.[r] ? "✓" : "—"));
    return `| ${feat} | ${cells.join(" | ")} |`;
  });
  return [header, sep, ...rows].join("\n");
}

function buildAiBrief(
  options: RbacPlanOptions,
  config: DnaConfig | null,
  inventory: SurfaceInventory,
  matrix: Record<string, Record<string, boolean>>,
): string {
  const roles = normalizeRoles(options.roles);
  const feature = options.feature ?? "platform";
  const deny = options.denyByDefault !== false;
  const zeroTrust = options.zeroTrust !== false;

  const sections: string[] = [
    "# DNA RBAC Implementation Plan",
    "",
    "_Generated by DNA by Humaan. Give this entire document to your AI tool before any RBAC work._",
    "",
    "## User requirement (plain language)",
    "",
    options.quote?.trim() ||
      `Implement RBAC for ${feature}. Roles: ${roles.join(", ")}. Default deny: ${deny}.`,
    "",
    "## Policy",
    "",
    `- **Default deny:** ${deny ? "YES — no user sees or accesses anything unless explicitly granted" : "NO"}`,
    `- **Zero trust:** ${zeroTrust ? "YES — verify every request server-side; never trust UI hiding alone" : "NO"}`,
    `- **Roles:** ${roles.join(", ")}`,
    `- **Feature scope:** ${feature}`,
    `- **Project:** ${config?.projectName ?? "unknown"}`,
    "",
    "## Why RBAC implementations fail (read this first)",
    "",
    "Common failure — exactly what happened in the dashboard scenario:",
    "",
    "1. AI adds an auth check on one API route but **does not hide menus, notifications, or nav items**",
    "2. UI still renders all sidebar links; user refreshes and **still sees restricted items**",
    "3. Routes are not guarded — user can navigate directly via URL",
    "4. Notifications and actions (shut down, settings, exports) remain visible",
    "5. No permission matrix — permissions are inconsistent across layers",
    "",
    "**DNA rule:** RBAC is not done until ALL layers pass the verification checklist below.",
    "",
    "## Implementation phases (complete in order — do not skip)",
    "",
    "### Phase 1 — Permission matrix (source of truth)",
    "",
    "Create `.DNA/CellularMemory/prefrontalCortex/rbac-permission-matrix.md` and enforce it everywhere.",
    "",
    "See matrix below. Admin approves before implementation continues.",
    "",
    matrixMarkdown(matrix, roles),
    "",
    "### Phase 2 — Server enforcement (zero trust)",
    "",
    "- Middleware on **every** API route and server action",
    "- Default **403** when role lacks permission",
    "- Never rely on frontend-only checks",
    "- Log denied access attempts",
    "",
    "Surfaces to protect:",
    ...inventory.apis.map((a) => `- API \`${a.path}\` (${a.source})`),
    ...(inventory.apis.length === 0 ? ["- _(scan found no API patterns — search codebase manually)_"] : []),
    "",
    "### Phase 3 — Route guards (frontend router)",
    "",
    "- Wrap protected routes with role guard",
    "- Redirect unauthorized users to `/unauthorized` or login",
    "- Block direct URL access",
    "",
    "Routes found:",
    ...inventory.routes.map((r) => `- \`${r.path}\` (${r.source})`),
    ...inventory.pages.map((p) => `- \`${p.path}\` (${p.source})`),
    ...(inventory.routes.length === 0 && inventory.pages.length === 0
      ? ["- _(scan found no routes — search router config manually)_"]
      : []),
    "",
    "### Phase 4 — UI surface hiding (menus, notifications, actions)",
    "",
    "**This is the step that was missed in the dashboard scenario.**",
    "",
    "For each menu item, notification type, button, and widget:",
    "- Hide if user's role lacks permission in matrix",
    "- Do not render DOM nodes (not just `display:none` on wrappers)",
    "- Filter notification feeds server-side AND client-side",
    "",
    "Menu/nav files to audit:",
    ...inventory.menus.map((m) => `- ${m.source}`),
    ...(inventory.menus.length === 0 ? ["- Search for `menuItems`, `navItems`, `sidebar`"] : []),
    "",
    "Notification surfaces to audit:",
    ...inventory.notifications.map((n) => `- ${n.source}`),
    ...(inventory.notifications.length === 0
      ? ["- Search for `notification`, `toast`, `NotificationCenter`"]
      : []),
    "",
    "### Phase 5 — Role management (where admins grant access)",
    "",
    "- Document where admins assign roles (admin panel, database, IdP)",
    "- No employee accesses platform until admin grants a role",
    "- Seed only admin in dev; never default all users to admin",
    "",
    "### Phase 6 — Tests & verification checklist",
    "",
    "Before marking complete, test **each role** with a fresh browser session:",
    "",
    "- [ ] Log in as employee with **no role** → cannot access platform",
    "- [ ] Log in as manager → sees only manager-permitted menus and routes",
    "- [ ] Refresh page → menus and notifications still correct (no flash of forbidden UI)",
    "- [ ] Direct URL to forbidden route → blocked",
    "- [ ] API call to forbidden endpoint → 403",
    "- [ ] Notifications for forbidden actions → not shown",
    "- [ ] Admin can access admin-only surfaces",
    "- [ ] Permission matrix doc matches implementation",
    "- [ ] `dna validate` passes",
    "",
    "## Knowledge to load",
    "",
    "- `.DNA/knowledge/security/rbac-fundamentals.dna.md`",
    "- `.DNA/knowledge/security/zero-trust.dna.md`",
    "- `.DNA/knowledge/security/ui-surface-checklist.dna.md`",
    "- `.DNA/behaviour/security.behaviour.md`",
    "- `.DNA/workflows/rbac.workflow.md`",
    "",
    "## neuralNetwork intent",
    "",
    "Use intent: `implement_rbac`",
    "",
    "## After completion",
    "",
    "1. Update `DNA/Impressions/security/security-baseline.md` with RBAC model",
    "2. Update `.DNA/CellularMemory/prefrontalCortex/decisions.md`",
    "3. Run `dna validate`",
    "4. Record any unfinished items in `prefrontalCortex/next-actions.md`",
    "",
    "## Surface inventory",
    "",
    formatInventorySummary(inventory),
    "",
  ];

  return sections.join("\n");
}

export async function generateRbacPlan(options: RbacPlanOptions): Promise<RbacPlanResult> {
  const { root } = options;
  const roles = normalizeRoles(options.roles);
  const feature = options.feature ?? "platform";

  const config = await loadDnaConfig(root);
  if (!config) {
    throw new Error("DNA not installed. Run `dna init` first.");
  }

  try {
    await installKnowledgePackById(root, "security/rbac-zero-trust", config.channel);
  } catch {
    // bundled pack should always exist
  }

  const inventory = await scanSurfaceInventory(root);
  const matrix = buildPermissionMatrix(roles, feature, inventory);
  const context = buildAiBrief(options, config, inventory, matrix);

  const planDir = join(root, ".DNA", "plans");
  const slug = feature.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  const planPath = join(planDir, `rbac-${slug}.md`);
  const matrixPath = join(root, ".DNA", "CellularMemory", "prefrontalCortex", "rbac-permission-matrix.md");
  const matrixJsonPath = join(root, ".DNA", "templates", "rbac", "permission-matrix.json");

  const matrixDoc = `# RBAC Permission Matrix

Feature: ${feature}
Roles: ${roles.join(", ")}
Default deny: ${options.denyByDefault !== false ? "yes" : "no"}
Zero trust: ${options.zeroTrust !== false ? "yes" : "no"}

${matrixMarkdown(matrix, roles)}

## Management

Admins grant roles via: _document your admin UI or provisioning flow here_

## Verification

See \`.DNA/plans/rbac-${slug}.md\` Phase 6 checklist.
`;

  await writeFileEnsured(planPath, context);
  await writeFileEnsured(matrixPath, matrixDoc);
  await writeJsonFile(matrixJsonPath, {
    feature,
    roles,
    denyByDefault: options.denyByDefault !== false,
    zeroTrust: options.zeroTrust !== false,
    quote: options.quote,
    matrix,
    generatedAt: new Date().toISOString(),
  });

  const nextActionsPath = join(root, ".DNA", "CellularMemory", "prefrontalCortex", "next-actions.md");
  const append = `\n- [ ] Complete RBAC for ${feature} — see .DNA/plans/rbac-${slug}.md\n`;
  if (await fileExists(nextActionsPath)) {
    const existing = await readFile(nextActionsPath, "utf-8");
    await writeFileEnsured(nextActionsPath, existing + append);
  } else {
    await writeFileEnsured(nextActionsPath, `# Next Actions\n${append}`);
  }

  return { planPath, matrixPath, matrixJsonPath, context, inventory };
}

export function parseRolesInput(input: string): string[] {
  return input.split(/[,;|]/).map((r) => r.trim()).filter(Boolean);
}

export { STANDARD_ROLES_HELP };
