import { join } from "node:path";
import { readFile } from "node:fs/promises";
import type { DnaConfig } from "@superhumaan/dna-config";
import { IMPRESSIONS_DIR } from "@superhumaan/dna-config";
import { writeFileEnsured, fileExists } from "../fs.js";
import { loadDnaConfig } from "../validator.js";
import { analyzeProject, type DeepAnalysis } from "./analyze.js";

export interface DocumentFromCodeOptions {
  root: string;
  /** Skip files that already have real content (default true) */
  merge?: boolean;
  /** Overwrite all target files */
  force?: boolean;
}

export interface DocumentFromCodeResult {
  filesWritten: string[];
  filesSkipped: string[];
  analysis: DeepAnalysis;
}

function header(title: string): string {
  return `# ${title}\n\n_Documented from codebase analysis by DNA by Humaan. Review and refine._\n\n`;
}

function isTemplateContent(content: string): boolean {
  if (content.includes("Documented from codebase analysis")) return false;
  if (content.includes("_TBD_")) return true;
  if (content.includes("_Define your")) return true;
  if (content.includes("_Map major features")) return true;
  if (content.includes("_Generated by DNA by Humaan")) return true;
  if (content.length < 200) return true;
  return false;
}

function buildArchitectureDocs(analysis: DeepAnalysis, config: DnaConfig | null): Record<string, string> {
  const { scan, structure, inventory, authPatterns, integrations } = analysis;
  const stack = config?.stack;
  const now = new Date().toISOString().split("T")[0];

  const routeList =
    inventory.routes.length > 0
      ? inventory.routes
          .slice(0, 15)
          .map((r) => `- \`${r.path}\` (${r.source})`)
          .join("\n")
      : "_No routes detected via static analysis._";

  const apiList =
    inventory.apis.length > 0
      ? inventory.apis
          .slice(0, 15)
          .map((a) => `- \`${a.path}\` (${a.source})`)
          .join("\n")
      : "_No API endpoints detected._";

  const integrationTable =
    integrations.length > 0
      ? [
          "| Service | Detected in |",
          "|---------|-------------|",
          ...integrations.map((i) => `| ${i.name} | ${i.sources[0] ?? "—"} |`),
        ].join("\n")
      : "| Service | Purpose | Auth Method |\n|---------|---------|-------------|\n| _TBD_ | — | — |";

  const authSection =
    authPatterns.length > 0
      ? authPatterns.map((a) => `- ${a.type} in \`${a.source}\``).join("\n")
      : "_No auth patterns detected — verify manually._";

  return {
    "architecture/solution-architecture.md": `${header("Solution Architecture")}

## As-is stack (detected ${now})

| Layer | Technology |
|-------|------------|
| Frontend | ${scan.frontend ?? stack?.frontend ?? "not detected"} |
| Backend | ${scan.backend ?? stack?.backend ?? "not detected"} |
| Database | ${scan.database ?? stack?.database ?? "not detected"} |
| Platform | ${stack?.platform ?? "not configured"} |
| Hosting | ${stack?.hosting ?? "not configured"} |
| Testing | ${scan.testFramework ?? stack?.testing ?? "not detected"} |
| CI/CD | ${scan.ciCd.length ? scan.ciCd.join(", ") : "none detected"} |
| Docker | ${scan.docker ? "yes" : "no"} |

## Source layout

- Top-level: ${structure.topLevelDirs.join(", ")}
- Source roots: ${structure.sourceRoots.join(", ")}
- Component areas: ${structure.componentDirs.length ? structure.componentDirs.join(", ") : "none detected"}
- API areas: ${structure.apiDirs.length ? structure.apiDirs.join(", ") : "none detected"}

## Architecture notes

- Features folder: ${structure.hasFeaturesFolder ? "present (vertical slice layout)" : "not present — consider feature folders for IVF Phase 4"}
- Admin routes: ${structure.hasAdminRoute ? "detected" : "not detected"}
- Central middleware: ${structure.hasMiddlewareDir ? "present" : "not detected — needed for RBAC/runtime"}
`,

    "architecture/system-boundaries.md": `${header("System Boundaries")}

## In scope (detected)

- Application source under: ${structure.sourceRoots.join(", ")}
${scan.backend ? `- API server (${scan.backend})` : ""}
${scan.frontend ? `- Frontend (${scan.frontend})` : ""}
${scan.database ? `- Database layer (${scan.database})` : ""}
${scan.ciCd.length ? `- CI/CD: ${scan.ciCd.join(", ")}` : ""}

## Module map

${structure.componentDirs.length ? structure.componentDirs.map((d) => `- \`${d}/components/\``).join("\n") : "_Component directories not clearly separated._"}

## Out of scope

_Define what is explicitly outside this system's boundaries._
`,

    "architecture/data-flow.md": `${header("Data Flow")}

## Request flow (inferred)

1. Client → ${scan.frontend ?? "frontend"}
2. ${scan.backend ? `Frontend → API (${scan.backend})` : "Frontend → backend (not detected)"}
3. ${scan.database ? `API → Database (${scan.database})` : "API → data store (not detected)"}
4. Response returned to client

## Routes detected

${routeList}

## API endpoints detected

${apiList}

## Auth flow

${authSection}
`,

    "architecture/integration-map.md": `${header("Integration Map")}

## External integrations (detected from imports)

${integrationTable}

## Environment

${scan.envFiles.length ? `Environment files present: ${scan.envFiles.join(", ")}` : "No .env files detected in scan."}
${scan.securityRisks.length ? `\n### Security notes\n\n${scan.securityRisks.map((r) => `- ⚠ ${r}`).join("\n")}` : ""}
`,

    "security/security-baseline.md": `${header("Security Baseline")}

## Compliance setting

${config?.compliance ?? "none"}

## Detected auth

${authSection}

## Baseline gaps

${scan.securityRisks.length ? scan.securityRisks.map((r) => `- ⚠ ${r}`).join("\n") : "- No immediate risks flagged by scan"}
${!scan.testFramework && structure.testFileCount === 0 ? "- ⚠ No test framework or test files detected" : ""}
${authPatterns.length === 0 ? "- ⚠ No auth patterns detected — verify access control" : ""}
`,

    "product/feature-map.md": `${header("Feature Map")}

## Surfaces detected

| Surface | Count |
|---------|-------|
| Routes | ${inventory.routes.length} |
| API endpoints | ${inventory.apis.length} |
| App pages | ${inventory.pages.length} |
| Menu/nav files | ${inventory.menus.length} |

## Feature status

| Feature | Status | Notes |
|---------|--------|-------|
| Core app | in progress | Detected from codebase |
${structure.hasAdminRoute ? "| Admin | partial | Admin route group detected |" : "| Admin | planned | No admin route group — see IVF plan |"}
${authPatterns.length ? "| Auth | partial | Patterns detected — centralize middleware |" : "| Auth | planned | No auth detected |"}
`,
  };
}

function buildSystemMap(analysis: DeepAnalysis, config: DnaConfig | null): string {
  const { scan, structure, inventory, integrations } = analysis;
  const now = new Date().toISOString().split("T")[0];

  return `# System Map

_Last updated: ${now} — generated from codebase analysis._

## Project

**${config?.projectName ?? "project"}** — ${config?.description ?? "No description."}

## Stack

- Frontend: ${scan.frontend ?? config?.stack.frontend ?? "TBD"}
- Backend: ${scan.backend ?? config?.stack.backend ?? "TBD"}
- Database: ${scan.database ?? config?.stack.database ?? "TBD"}

## Directory structure

\`\`\`
${structure.topLevelDirs.join("\n")}
\`\`\`

## Components

${structure.componentDirs.length ? structure.componentDirs.map((d) => `- \`${d}\``).join("\n") : "- _Not clearly separated_"}

## Routes (${inventory.routes.length})

${inventory.routes.slice(0, 20).map((r) => `- \`${r.path}\``).join("\n") || "_None detected_"}

## APIs (${inventory.apis.length})

${inventory.apis.slice(0, 20).map((a) => `- \`${a.path}\``).join("\n") || "_None detected_"}

## Integrations

${integrations.map((i) => `- ${i.name}`).join("\n") || "_None detected_"}
`;
}

function buildIvfGapsMarkdown(analysis: DeepAnalysis): string {
  const lines = [
    "# IVF Gap Matrix",
    "",
    "_Vertical function gaps for Integrating Vertical Functions. Updated by `dna plan ivf`._",
    "",
    "| Priority | Vertical | Current | Target | Restructure |",
    "|----------|----------|---------|--------|-------------|",
  ];

  for (const g of analysis.verticalGaps) {
    lines.push(
      `| ${g.priority} | ${g.name} | ${g.currentState.replace(/\|/g, "/")} | ${g.targetState.replace(/\|/g, "/")} | ${g.restructureNeeded ? "yes" : "no"} |`,
    );
  }

  lines.push("", "## Actions by vertical", "");
  for (const g of analysis.verticalGaps) {
    lines.push(`### ${g.name} (${g.priority})`, "", g.why, "", ...g.actions.map((a) => `- ${a}`), "");
  }

  return lines.join("\n");
}

export async function documentFromCode(
  options: DocumentFromCodeOptions,
): Promise<DocumentFromCodeResult> {
  const { root, force = false } = options;
  const merge = options.merge !== false;

  const config = await loadDnaConfig(root);
  const analysis = await analyzeProject(root);
  const docs = buildArchitectureDocs(analysis, config);

  const filesWritten: string[] = [];
  const filesSkipped: string[] = [];

  for (const [relPath, content] of Object.entries(docs)) {
    const fullPath = join(root, IMPRESSIONS_DIR, relPath);
    if (merge && !force && (await fileExists(fullPath))) {
      const existing = await readFile(fullPath, "utf-8");
      if (!isTemplateContent(existing)) {
        filesSkipped.push(relPath);
        continue;
      }
    }
    await writeFileEnsured(fullPath, content);
    filesWritten.push(relPath);
  }

  const systemMapPath = join(root, ".DNA", "CellularMemory", "parietalLobe", "system-map.md");
  if (force || !(await fileExists(systemMapPath)) || merge) {
    const existing = (await fileExists(systemMapPath))
      ? await readFile(systemMapPath, "utf-8")
      : "";
    if (force || !existing || isTemplateContent(existing)) {
      await writeFileEnsured(systemMapPath, buildSystemMap(analysis, config));
      filesWritten.push(".DNA/CellularMemory/parietalLobe/system-map.md");
    }
  }

  const gapsPath = join(root, ".DNA", "CellularMemory", "prefrontalCortex", "ivf-gaps.md");
  await writeFileEnsured(gapsPath, buildIvfGapsMarkdown(analysis));
  filesWritten.push(".DNA/CellularMemory/prefrontalCortex/ivf-gaps.md");

  const summaryPath = join(root, ".DNA", "CellularMemory", "hippocampus", "project-summary.md");
  if (config && ((await fileExists(summaryPath)) ? isTemplateContent(await readFile(summaryPath, "utf-8")) : true)) {
    await writeFileEnsured(
      summaryPath,
      `# Project Summary

**${config.projectName}**

${config.description ?? "Documented from existing codebase."}

## Stack (detected)

- Frontend: ${analysis.scan.frontend ?? config.stack.frontend ?? "TBD"}
- Backend: ${analysis.scan.backend ?? config.stack.backend ?? "TBD"}
- Database: ${analysis.scan.database ?? config.stack.database ?? "TBD"}
- Stage: ${config.stage}

## Analysis

- Routes: ${analysis.inventory.routes.length}
- APIs: ${analysis.inventory.apis.length}
- Integrations: ${analysis.integrations.map((i) => i.name).join(", ") || "none detected"}
`,
    );
    filesWritten.push(".DNA/CellularMemory/hippocampus/project-summary.md");
  }

  return { filesWritten, filesSkipped, analysis };
}

export function formatDocumentResult(result: DocumentFromCodeResult): string {
  const lines = [
    "DNA Document from Code",
    "======================",
    "",
    `Written: ${result.filesWritten.length} file(s)`,
    ...result.filesWritten.map((f) => `  ✓ ${f}`),
  ];
  if (result.filesSkipped.length) {
    lines.push("", `Skipped (existing content): ${result.filesSkipped.length}`);
    result.filesSkipped.forEach((f) => lines.push(`  — ${f}`));
  }
  return lines.join("\n");
}
