import { join } from "node:path";
import type { DnaConfig } from "@superhumaan/dna-config";
import { writeFileEnsured } from "../fs.js";
import { loadDnaConfig } from "../validator.js";
import { ensureKnowledgeInstalled } from "../marketplace/ensure.js";
import {
  getArchetypeMeta,
  getMethodologyMeta,
  knowledgePackIdsForProfile,
  parseArchetypeInput,
  parseMethodologyInput,
  resolveDeliveryProfile,
} from "./catalog.js";
import { readCustomProfileContent } from "./profile.js";

export interface MethodologyPlanOptions {
  root: string;
  methodology?: string;
  companyArchetype?: string;
  quote?: string;
}

export interface MethodologyPlanResult {
  planPath: string;
  context: string;
}

export async function generateMethodologyPlan(
  options: MethodologyPlanOptions,
): Promise<MethodologyPlanResult> {
  const config = await loadDnaConfig(options.root);
  const existing = resolveDeliveryProfile(config);
  const methodology = options.methodology
    ? parseMethodologyInput(options.methodology)
    : existing.methodology;
  const companyArchetype = options.companyArchetype
    ? parseArchetypeInput(options.companyArchetype)
    : existing.companyArchetype;
  const profile = resolveDeliveryProfile({
    ...(config ?? ({} as DnaConfig)),
    delivery: {
      ...existing,
      methodology,
      companyArchetype,
    },
  });

  await ensureKnowledgeInstalled(options.root, knowledgePackIdsForProfile(profile));

  const meta = getMethodologyMeta(profile.methodology);
  const archetype = getArchetypeMeta(profile.companyArchetype);
  const custom = await readCustomProfileContent(options.root, profile);

  const lines = [
    "# Methodology Plan",
    "",
    `_Generated by DNA. Use with \`dna context methodology\` before writing tickets or specs._`,
    "",
    `**Project:** ${config?.projectName ?? "unknown"}`,
    `**Methodology:** ${meta.name}`,
    `**Archetype:** ${archetype.name}`,
    `**Ticket system:** ${profile.ticketSystem}`,
    `**Doc system:** ${profile.docSystem}`,
    `**Hierarchy:** ${profile.hierarchy.join(" → ")}`,
    "",
    options.quote ? `## User request\n\n${options.quote}\n` : "",
    "## How this team works",
    "",
    meta.description,
    "",
    archetype.packId ? `Company pattern: ${archetype.description}` : "",
    "",
    "## Ceremonies",
    "",
    ...profile.ceremonies.map((c) => `- ${c}`),
    "",
    "## AI rules for tickets and documents",
    "",
    "1. Run `dna context methodology` before creating tickets or specs",
    "2. Match the work hierarchy — do not invent a different structure",
    "3. Use ticket fields and labels from methodology + custom profile",
    "4. DNA code quality gates still apply — methodology shapes artifacts, not test coverage",
    "5. For code changes: feature factory roles adapt plan shape to this methodology",
    "",
    "## Knowledge packs to load",
    "",
    ...knowledgePackIdsForProfile(profile).map((p) => `- \`.DNA/knowledge/${p}/\``),
    "",
    "## Stem packs",
    "",
    "- `/create-ticket` — write tickets in org format",
    "- `/write-spec` — PRD / design doc / RFC",
    "- `/break-down-work` — split initiative → stories",
    "- `/align-delivery` — audit plan against methodology",
  ];

  if (custom) {
    lines.push("", "## Custom profile", "", custom);
  }

  const planPath = join(options.root, ".DNA", "delivery", "methodology-plan.md");
  const content = lines.filter(Boolean).join("\n");
  await writeFileEnsured(planPath, content);

  return { planPath, context: content };
}
