import { join } from "node:path";
import type { DnaConfig } from "@superhumaan/dna-config";
import { IMPRESSIONS_DIR } from "@superhumaan/dna-config";
import { writeFileEnsured } from "../fs.js";
import { loadDnaConfig } from "../validator.js";
import { ensureKnowledgeInstalled } from "../marketplace/ensure.js";
import {
  getLifecycleMeta,
  getMethodMeta,
  getTeamMeta,
  knowledgePackIdsForDiscoveryProfile,
  parseLifecycleInput,
  parseMethodInput,
  parseTeamInput,
  resolveDiscoveryProfile,
} from "./catalog.js";
import { readCustomDiscoveryContent } from "./profile.js";
import { scaffoldDiscoveryImpressions } from "./sync.js";

export interface DiscoveryPlanOptions {
  root: string;
  lifecycleStage?: string;
  teamModel?: string;
  quote?: string;
}

export interface DiscoveryPlanResult {
  planPath: string;
  context: string;
}

export interface ResearchPlanOptions {
  root: string;
  method: string;
  quote?: string;
}

export interface ResearchPlanResult {
  planPath: string;
  context: string;
}

export async function generateDiscoveryPlan(
  options: DiscoveryPlanOptions,
): Promise<DiscoveryPlanResult> {
  const config = await loadDnaConfig(options.root);
  const existing = resolveDiscoveryProfile(config);
  const lifecycleStage = options.lifecycleStage
    ? parseLifecycleInput(options.lifecycleStage)
    : existing.lifecycleStage;
  const teamModel = options.teamModel ? parseTeamInput(options.teamModel) : existing.teamModel;
  const profile = resolveDiscoveryProfile({
    ...(config ?? ({} as DnaConfig)),
    discovery: { ...existing, lifecycleStage, teamModel },
  });

  await ensureKnowledgeInstalled(options.root, knowledgePackIdsForDiscoveryProfile(profile));
  await scaffoldDiscoveryImpressions(options.root);

  const lifecycle = getLifecycleMeta(profile.lifecycleStage);
  const team = getTeamMeta(profile.teamModel);
  const custom = await readCustomDiscoveryContent(options.root, profile);

  const lines = [
    "# Discovery Plan",
    "",
    `_Generated by DNA. Use with \`dna context discovery\` before product shaping, research, or UX work._`,
    "",
    `**Project:** ${config?.projectName ?? "unknown"}`,
    `**Lifecycle stage:** ${lifecycle.name}`,
    `**Team model:** ${team.name}`,
    "",
    options.quote ? `## User request\n\n${options.quote}\n` : "",
    "## Product lifecycle position",
    "",
    lifecycle.description,
    "",
    `**Recommended methods at this stage:** ${lifecycle.recommendedMethods.join(", ")}`,
    "",
    "## Active discovery practices",
    "",
    `**Processes:** ${profile.activeProcesses.join(", ") || "(none)"}`,
    `**Methods:** ${profile.activeMethods.join(", ") || "(none)"}`,
    `**Events:** ${profile.activeEvents.join(", ") || "(none)"}`,
    "",
    "## AI rules for discovery work",
    "",
    "1. Run `dna context discovery` before research plans, PRDs, or opportunity prioritisation",
    "2. Match artifacts to lifecycle stage — do not skip validation gates",
    "3. Log research in `DNA/Impressions/product/discovery-log.md`",
    "4. Synthesise insights into `opportunity-tree.md` and `research-insights.md`",
    "5. Track assumptions in `assumptions-risks.md` with test status",
    "6. When validated, hand off via `discovery/handoff-to-delivery` → `ai/feature-request.md`",
    "7. Engineering quality gates still apply after handoff",
    "",
    "## Impressions scaffolded",
    "",
    `- \`${IMPRESSIONS_DIR}/product/discovery-log.md\``,
    `- \`${IMPRESSIONS_DIR}/product/opportunity-tree.md\``,
    `- \`${IMPRESSIONS_DIR}/product/assumptions-risks.md\``,
    `- \`${IMPRESSIONS_DIR}/product/research-insights.md\``,
    `- \`${IMPRESSIONS_DIR}/product/pmf-signals.md\``,
    "",
    "## Knowledge packs",
    "",
    ...knowledgePackIdsForDiscoveryProfile(profile).map((p) => `- \`.DNA/knowledge/${p}/\``),
    "",
    "## Stem packs",
    "",
    "- `/discovery-setup` — configure discovery profile",
    "- `/plan-research` — plan a specific study",
    "- `/synthesize-research` — findings → opportunities",
    "- `/prioritize-opportunities` — rank backlog",
    "- `/pmf-check` — review PMF signals",
    "- `/handoff-to-engineering` — start feature factory",
  ];

  if (custom) {
    lines.push("", "## Custom profile", "", custom);
  }

  const planPath = join(options.root, ".DNA", "discovery", "discovery-plan.md");
  const content = lines.filter(Boolean).join("\n");
  await writeFileEnsured(planPath, content);

  return { planPath, context: content };
}

export async function generateResearchPlan(options: ResearchPlanOptions): Promise<ResearchPlanResult> {
  const config = await loadDnaConfig(options.root);
  const profile = resolveDiscoveryProfile(config);
  const methodId = parseMethodInput(options.method);
  const method = getMethodMeta(methodId);

  await ensureKnowledgeInstalled(options.root, [method.packId, ...knowledgePackIdsForDiscoveryProfile(profile)]);
  await scaffoldDiscoveryImpressions(options.root);

  const lines = [
    `# Research Plan — ${method.name}`,
    "",
    `_Generated by DNA. Method pack: \`${method.packId}\`_`,
    "",
    `**Project:** ${config?.projectName ?? "unknown"}`,
    `**Lifecycle:** ${getLifecycleMeta(profile.lifecycleStage).name}`,
    `**Research type:** ${method.researchType}`,
    "",
    options.quote ? `## Research question\n\n${options.quote}\n` : "",
    "## Study outline",
    "",
    `1. Define hypothesis and success criteria`,
    `2. Recruit participants appropriate for ${method.name}`,
    `3. Run sessions using artifacts from \`.DNA/knowledge/${method.packId}/artifacts.dna.md\``,
    `4. Synthesise within 48 hours — \`/synthesize-research\``,
    `5. Update assumptions register and opportunity tree`,
    `6. Run \`dna sync discovery\` to persist findings`,
    "",
    "## DNA sync checklist",
    "",
    "- [ ] Entry in `discovery-log.md` (date, method, participants, goal)",
    "- [ ] Insights added to `research-insights.md`",
    "- [ ] New/changed opportunities in `opportunity-tree.md`",
    "- [ ] Assumption status updated in `assumptions-risks.md`",
    "- [ ] If PMF-related, update `pmf-signals.md`",
    "",
    "## Next steps",
    "",
    "- `dna context discovery` — load full discovery context",
    "- `/handoff-to-engineering` — when opportunity is validated",
  ];

  const planPath = join(options.root, ".DNA", "discovery", "research-plans", `${methodId}.md`);
  const content = lines.join("\n");
  await writeFileEnsured(planPath, content);

  return { planPath, context: content };
}
