import { join } from "node:path";
import type { DnaConfig } from "@superhumaan/dna-config";
import { writeFileEnsured } from "../fs.js";
import { loadDnaConfig } from "../validator.js";
import { ensureKnowledgeForPaths } from "../marketplace/ensure.js";
import {
  COMPLIANCE_FRAMEWORK_CATALOG,
  FRAMEWORK_TIER_FOCUS,
  getFramework,
  parseFrameworksInput,
  parseOrgTier,
  type ComplianceFramework,
  type OrgTier,
} from "./catalog.js";
import {
  CONTROL_DOMAINS,
  ORG_TIER_PROFILES,
  frameworkKnowledgeFiles,
  getTierProfile,
  inferOrgTierFromStage,
} from "./tiers.js";
import {
  buildGdprDocumentChecklistMarkdown,
  formatGdprDocumentCatalog,
  gdprDocumentsForTier,
} from "./gdpr-doc-catalog.js";
import { installGdprExamples } from "./install-gdpr-examples.js";

export interface CompliancePlanOptions {
  root: string;
  /** One or more frameworks: gdpr, hipaa, iso27001, soc2, pci_dss, uk_gdpr */
  frameworks: ComplianceFramework[];
  tier?: OrgTier;
  quote?: string;
}

export interface CompliancePlanResult {
  planPath: string;
  matrixPath: string;
  context: string;
  tier: OrgTier;
  frameworks: ComplianceFramework[];
}

function resolveTier(options: CompliancePlanOptions, config: DnaConfig | null): OrgTier {
  if (options.tier) return options.tier;
  if (config?.stage) return inferOrgTierFromStage(config.stage);
  return "startup";
}

function buildControlMatrixMarkdown(tier: OrgTier): string {
  const lines = [
    `# Compliance Control Matrix — ${getTierProfile(tier).name}`,
    "",
    "_Source of truth for engineering + GRC. Update when controls are implemented._",
    "",
    "| Domain | Requirement at this tier | Status | Owner | Evidence |",
    "| --- | --- | --- | --- | --- |",
  ];

  for (const domain of CONTROL_DOMAINS) {
    const req = domain.tiers[tier].replace(/\|/g, "\\|");
    lines.push(`| ${domain.name} | ${req} | ☐ | | |`);
  }

  lines.push("");
  return lines.join("\n");
}

function buildFrameworkSection(framework: ComplianceFramework, tier: OrgTier): string[] {
  const meta = getFramework(framework);
  const focus = FRAMEWORK_TIER_FOCUS[framework][tier];
  return [
    `### ${meta?.name ?? framework}`,
    "",
    meta?.description ?? "",
    "",
    `**Scope:** ${meta?.scope ?? "—"}`,
    "",
    `**Certification / attestation:** ${meta?.certification ?? "—"}`,
    "",
    `**Priority controls at ${tier} tier:**`,
    "",
    ...focus.map((c) => `- [ ] ${c}`),
    "",
    `**Knowledge:** ${frameworkKnowledgeFiles(framework).map((k) => `\`.DNA/knowledge/${k}\``).join(", ")}`,
    "",
  ];
}

function buildAiBrief(
  options: CompliancePlanOptions,
  config: DnaConfig | null,
  tier: OrgTier,
  gdprExampleCount = 0,
): string {
  const profile = getTierProfile(tier);
  const frameworks = options.frameworks;

  const sections: string[] = [
    "# DNA Compliance Implementation Plan",
    "",
    "_Generated by DNA by Humaan. Give this entire document to your AI tool before building features that touch personal, health, or payment data._",
    "",
    "## User requirement",
    "",
    options.quote?.trim() ||
      `Implement compliance controls for ${frameworks.join(", ")} at ${profile.name} (${tier}) maturity.`,
    "",
    "## Organisation tier",
    "",
    `- **Tier:** ${profile.name} (\`${tier}\`)`,
    `- **Typical size:** ${profile.teamSize}`,
    `- **Security ownership:** ${profile.securityStaff}`,
    `- **Review cadence:** ${profile.auditCadence}`,
    `- **Guidance:** ${profile.summary}`,
    `- **Project:** ${config?.projectName ?? "unknown"}`,
    `- **Config compliance:** ${config?.compliance ?? "none"}`,
    `- **Project stage:** ${config?.stage ?? "unknown"} (tier inferred if not specified)`,
    "",
    "## Frameworks in scope",
    "",
    ...frameworks.flatMap((f) => buildFrameworkSection(f, tier)),
    "## Cross-cutting control domains (all frameworks)",
    "",
    "Implement these at your tier **before** claiming framework compliance:",
    "",
    ...CONTROL_DOMAINS.map((d) => `- **${d.name}:** ${d.tiers[tier]}`),
    "",
    "## Engineering rules (non-negotiable at every tier)",
    "",
    "1. **Secrets** — never in repo; use env / Key Vault / Secrets Manager",
    "2. **Encryption** — TLS everywhere; at-rest for PII/PHI/payment data",
    "3. **Access** — default deny RBAC; MFA for admin; audit admin actions",
    "4. **Logging** — no PII/PHI/secrets in logs; redact in errors",
    "5. **AI** — no regulated data in third-party model prompts without DPA/BAA and legal sign-off",
    "6. **Vendors** — DPA for GDPR; BAA for HIPAA; list in Impressions subprocessors",
    "7. **Deletion** — implement erasure/export paths; document retention",
    "8. **Breach** — know your notification window (GDPR 72h, HIPAA 60d, etc.)",
    "",
    "## Implementation phases",
    "",
    "1. **Discover** — data inventory: what you collect, where stored, lawful basis, retention",
    "2. **Gap** — compare inventory to tier matrix in `.DNA/CellularMemory/prefrontalCortex/compliance-control-matrix.md`",
    "3. **Design** — privacy-by-design for new features; DPIA/BAA before new data types",
    "4. **Build** — technical controls (encryption, auth, audit, consent UI)",
    "5. **Document** — update `DNA/Impressions/security/data-protection.md` and `compliance/compliance-overview.md`",
    "6. **Verify** — checklist per framework; `dna validate`; security review",
    "7. **Operate** — access reviews, vendor reviews, incident drills per tier cadence",
    "",
    "## Tier progression",
    "",
    "| From | Signals to move up |",
    "| --- | --- |",
    "| startup → sme | Enterprise customers asking for security questionnaire; >25 staff; handling more PII |",
    "| sme → corporate | SOC 2 / ISO requested in RFPs; dedicated security hire; regulated industry |",
    "| corporate → enterprise | Multi-region; certification mandatory; board risk committee |",
    "",
    "## Knowledge to load (mandatory)",
    "",
    "- `compliance/tiered-standards` pack (auto-installed)",
    `- \`.DNA/knowledge/compliance/tiers/${tier}.dna.md\``,
    ...frameworks.flatMap((f) =>
      frameworkKnowledgeFiles(f).map((k) => `- \`.DNA/knowledge/${k}\``),
    ),
    "- `.DNA/behaviour/security.behaviour.md`",
    "- `.DNA/neuralNetwork.json` → intent `implement_compliance_controls`",
    "",
    "## Definition of done",
    "",
    "- [ ] Control matrix updated with owners and evidence links",
    "- [ ] No secrets in codebase; `.env.example` complete",
    "- [ ] Data inventory documented in Impressions",
    "- [ ] Framework-specific checklist complete for current tier",
    "- [ ] Engineering team can explain lawful basis / PHI scope / card data scope",
    "- [ ] `dna validate` passes",
    "",
    "## Do not",
    "",
    "- Claim ISO/HIPAA/SOC 2 certification without audit",
    "- Store PHI or card data to avoid using compliant processors",
    "- Ship analytics/AI on personal data without documented lawful basis",
    "- Skip tier-appropriate controls because \"we're small\" — startups still need baselines",
    "",
  ];

  const hasGdpr = options.frameworks.some((f) => f === "gdpr" || f === "uk_gdpr");
  if (hasGdpr) {
    const docCount = gdprDocumentsForTier(tier, { includeAi: true }).length;
    sections.push(
      "## GDPR document pack (UK required documents)",
      "",
      `DNA includes **${gdprExampleCount} scrubbed UK GDPR templates** (required document types).`,
      `${docCount} documents are required at **${tier}** tier (checklist below).`,
      "",
      "Installed to `.DNA/knowledge/compliance/gdpr/examples/` — start with `INDEX.md`.",
      "",
      "When AI drafts a document, **read the matching example first** (same slug), then customize:",
      "",
      ...gdprDocumentsForTier(tier, { includeAi: true })
        .slice(0, 15)
        .map((d) => `- [ ] **${d.title}** (\`${d.slug}\`) — ${d.folder}`),
      "",
      "Full checklist written to `.DNA/CellularMemory/prefrontalCortex/gdpr-document-checklist.md`",
      "",
    );
  }

  return sections.join("\n");
}

export async function generateCompliancePlan(
  options: CompliancePlanOptions,
): Promise<CompliancePlanResult> {
  if (!options.frameworks.length) {
    throw new Error(
      `No frameworks specified. Use: ${COMPLIANCE_FRAMEWORK_CATALOG.map((f) => f.id).join(", ")}`,
    );
  }

  const config = await loadDnaConfig(options.root);
  if (!config) {
    throw new Error("DNA not installed. Run `dna init` first.");
  }

  const tier = resolveTier(options, config);

  const knowledgePaths = [
    `compliance/tiers/${tier}.dna.md`,
    "compliance/tiers/overview.dna.md",
    "compliance/matrices/control-by-tier.dna.md",
    ...options.frameworks.flatMap((f) => frameworkKnowledgeFiles(f)),
  ];
  await ensureKnowledgeForPaths(options.root, knowledgePaths, config.channel);

  const hasGdprFramework = options.frameworks.some((f) => f === "gdpr" || f === "uk_gdpr");
  let gdprExampleCount = 0;
  if (hasGdprFramework) {
    const installed = await installGdprExamples(options.root);
    gdprExampleCount = installed.filter((p) => p.includes("/examples/") && p.endsWith(".md") && !p.endsWith("INDEX.md")).length;
  }

  const context = buildAiBrief(options, config, tier, gdprExampleCount);
  const slug = `${options.frameworks.join("-")}-${tier}`;
  const planPath = join(options.root, ".DNA", "plans", `compliance-${slug}.md`);
  const matrixPath = join(
    options.root,
    ".DNA",
    "CellularMemory",
    "prefrontalCortex",
    "compliance-control-matrix.md",
  );

  await writeFileEnsured(planPath, context);
  await writeFileEnsured(matrixPath, buildControlMatrixMarkdown(tier));

  const hasGdpr = options.frameworks.some((f) => f === "gdpr" || f === "uk_gdpr");
  if (hasGdpr) {
    const checklistPath = join(
      options.root,
      ".DNA",
      "CellularMemory",
      "prefrontalCortex",
      "gdpr-document-checklist.md",
    );
    await writeFileEnsured(
      checklistPath,
      buildGdprDocumentChecklistMarkdown(tier, true),
    );
  }

  return {
    planPath,
    matrixPath,
    context,
    tier,
    frameworks: options.frameworks,
  };
}

export function formatComplianceCatalog(): string {
  const lines = [
    "DNA Compliance Catalog — Tiered Standards",
    "=======================================",
    "",
    "Organisation tiers (control depth):",
    "",
  ];

  for (const t of ORG_TIER_PROFILES) {
    lines.push(`• ${t.id} — ${t.name} (${t.teamSize})`);
    lines.push(`  ${t.summary}`);
    lines.push("");
  }

  lines.push("Frameworks (dna plan compliance --frameworks <id>):", "");
  for (const f of COMPLIANCE_FRAMEWORK_CATALOG) {
    lines.push(`  ${f.id.padEnd(12)} ${f.name}`);
    lines.push(`               ${f.description}`);
    lines.push("");
  }

  lines.push("Tier inference from project stage:", "");
  lines.push("  new/mvp → startup | scaling → sme | enterprise → enterprise");
  lines.push("  legacy_modernisation/audit_remediation → corporate");
  lines.push("");
  lines.push(formatGdprDocumentCatalog());
  lines.push("");

  return lines.join("\n");
}

export { parseFrameworksInput, parseOrgTier, inferOrgTierFromStage };
