import type { DnaConfig, Recommendation, WizardAnswers } from "@humaan/dna-config";

function header(title: string): string {
  return `# ${title}\n\n_Generated by DNA by Humaan. Review and refine as your project evolves._\n\n`;
}

export function generateImpressions(
  config: DnaConfig,
  answers: WizardAnswers,
  recommendation: Recommendation,
): Record<string, string> {
  const desc = answers.projectDescription;
  const stack = config.stack;

  return {
    "product/product-overview.md": `${header("Product Overview")}

## What We're Building

${desc}

## Project

- **Name:** ${config.projectName}
- **Stage:** ${config.stage}
- **Compliance:** ${config.compliance}

## Solution Characteristics

${recommendation.solution.map((s) => `- ${s}`).join("\n")}
`,

    "product/user-types.md": `${header("User Types")}

## Primary Users

_Define your primary user personas here._

- End users
- Administrators
- API consumers (if applicable)

## Access Levels

- Guest / unauthenticated
- Authenticated user
- Admin / operator
`,

    "product/feature-map.md": `${header("Feature Map")}

## Core Features

_Map major features and their status here._

| Feature | Status | Priority |
|---------|--------|----------|
| _TBD_   | planned | —       |
`,

    "architecture/solution-architecture.md": `${header("Solution Architecture")}

## Stack

| Layer | Technology |
|-------|------------|
| Frontend | ${stack.frontend ?? "TBD"} |
| Backend | ${stack.backend ?? "TBD"} |
| Database | ${stack.database ?? "TBD"} |
| Platform | ${stack.platform ?? "TBD"} |
| Hosting | ${stack.hosting ?? "TBD"} |
| Testing | ${stack.testing ?? "TBD"} |

## Architecture Principles

${recommendation.solution.map((s) => `- ${s}`).join("\n")}
`,

    "architecture/system-boundaries.md": `${header("System Boundaries")}

## In Scope

- Application frontend
- API backend
- Database layer
- CI/CD pipeline

## Out of Scope

_Define what is explicitly outside this system's boundaries._
`,

    "architecture/data-flow.md": `${header("Data Flow")}

## Request Flow

1. Client request → Frontend
2. Frontend → API backend
3. API → Database
4. Response returned to client

## Data Stores

- Primary database: ${stack.database ?? "TBD"}
`,

    "architecture/integration-map.md": `${header("Integration Map")}

## External Integrations

| Service | Purpose | Auth Method |
|---------|---------|-------------|
| _TBD_   | —       | —           |
`,

    "security/security-baseline.md": `${header("Security Baseline")}

## Compliance

${config.compliance}

## Baseline Controls

${recommendation.security.map((s) => `- ${s}`).join("\n")}
`,

    "security/threat-model.md": `${header("Threat Model")}

## Assets

- User data
- Authentication credentials
- API keys and secrets

## Threats

| Threat | Likelihood | Impact | Mitigation |
|--------|------------|--------|------------|
| _TBD_  | —          | —      | —          |
`,

    "security/data-protection.md": `${header("Data Protection")}

## Data Classification

- Public
- Internal
- Confidential
- Restricted

## Retention

_Define data retention policies based on compliance requirements (${config.compliance})._
`,

    "qa/qa-strategy.md": `${header("QA Strategy")}

## Testing Approach

${recommendation.testing.map((t) => `- ${t}`).join("\n")}
`,

    "qa/test-plan.md": `${header("Test Plan")}

## Test Levels

- Unit tests
- Integration tests
- End-to-end tests
- Manual exploratory testing

## Coverage Goals

- Critical paths: 100%
- Business logic: 80%+
`,

    "qa/regression-risks.md": `${header("Regression Risks")}

## High-Risk Areas

| Area | Risk | Mitigation |
|------|------|------------|
| Authentication | High | Automated auth tests |
| Data mutations | High | Integration test suite |
`,

    "devops/deployment-model.md": `${header("Deployment Model")}

## Hosting

${stack.hosting ?? "TBD"}

## Deployment Strategy

- CI/CD on merge to main
- Staging environment for pre-production validation
- Production deployment with rollback capability
`,

    "devops/environments.md": `${header("Environments")}

| Environment | Purpose | URL |
|-------------|---------|-----|
| Development | Local dev | localhost |
| Staging | Pre-production | _TBD_ |
| Production | Live | _TBD_ |
`,

    "devops/rollback-plan.md": `${header("Rollback Plan")}

## Rollback Procedure

1. Identify failing deployment via runtime monitoring
2. Revert to previous release tag
3. Verify health checks pass
4. Create incident report in CellularMemory
`,

    "compliance/compliance-overview.md": `${header("Compliance Overview")}

## Applicable Frameworks

${config.compliance === "none" ? "No specific compliance framework selected." : config.compliance}

## Requirements

_Document compliance requirements and controls here._
`,

    "srs/software-requirements-specification.md": `${header("Software Requirements Specification")}

## Project

${desc}

## Functional Requirements

_FR-001: _TBD_

## Non-Functional Requirements

_NFR-001: System shall support automated testing_
_NFR-002: System shall have runtime error monitoring_
`,

    "release-notes/initial-release-notes.md": `${header("Initial Release Notes")}

## v0.1.0

- Initial project setup with DNA by Humaan
- Project intelligence and documentation scaffold generated
- Behaviour and CellularMemory initialised
`,

    "user-guides/getting-started.md": `${header("Getting Started")}

## Quick Start

1. Run \`dna init\` to set up DNA
2. Run \`dna scan\` to detect your stack
3. Run \`dna context cursor\` for AI-ready context
4. Run \`dna validate\` before committing

## Project

${desc}
`,
  };
}
