import type { DnaConfig, Recommendation, WizardAnswers } from "@superhumaan/dna-config";
import {
  BEHAVIOUR_FILES,
  CELLULAR_MEMORY_REGIONS,
  DNA_CONFIG_FILE,
  IMPRESSIONS_PATHS,
  NEURAL_NETWORK_FILE,
} from "@superhumaan/dna-config";
import { join } from "node:path";
import { writeFileEnsured, writeJsonFile } from "../fs.js";
import { generateNeuralNetwork } from "./neural-network.js";
import { generateBehaviourFiles } from "./behaviour.js";
import { generateImpressions } from "./impressions.js";
import { generateKnowledgePacks } from "./knowledge.js";
import { generateImmuneSystem } from "./immune-files.js";
import { generateCellularMemory } from "./cellular-memory.js";
import { generateWorkflows } from "./workflows.js";
import { generateTemplateFiles } from "./templates.js";
import { NEURAL_NETWORK_ALT } from "@superhumaan/dna-config";
import { ensureRuntimeDatabase } from "../storage/runtime-db.js";

export async function generateDnaStructure(
  root: string,
  config: DnaConfig,
  answers: WizardAnswers,
  recommendation: Recommendation,
): Promise<string[]> {
  const created: string[] = [];

  const configPath = join(root, DNA_CONFIG_FILE);
  await writeJsonFile(configPath, config);
  created.push(DNA_CONFIG_FILE);

  const neuralNetwork = generateNeuralNetwork(config);
  const neuralPath = join(root, NEURAL_NETWORK_FILE);
  await writeJsonFile(neuralPath, neuralNetwork);
  created.push(NEURAL_NETWORK_FILE);
  // Spec alias without extension
  await writeJsonFile(join(root, NEURAL_NETWORK_ALT), neuralNetwork);
  created.push(NEURAL_NETWORK_ALT);

  for (const [file, content] of Object.entries(generateBehaviourFiles(config))) {
    const path = join(root, ".DNA", "behaviour", file);
    await writeFileEnsured(path, content);
    created.push(`.DNA/behaviour/${file}`);
  }

  for (const [relPath, content] of Object.entries(
    generateImpressions(config, answers, recommendation),
  )) {
    const path = join(root, "DNA", "Impressions", relPath);
    await writeFileEnsured(path, content);
    created.push(`DNA/Impressions/${relPath}`);
  }

  for (const [relPath, content] of Object.entries(generateKnowledgePacks(config))) {
    const path = join(root, ".DNA", "knowledge", relPath);
    await writeFileEnsured(path, content);
    created.push(`.DNA/knowledge/${relPath}`);
  }

  for (const [file, content] of Object.entries(generateImmuneSystem())) {
    const path = join(root, ".DNA", "immuneSystem", file);
    await writeFileEnsured(path, content);
    created.push(`.DNA/immuneSystem/${file}`);
  }

  for (const [relPath, content] of Object.entries(generateCellularMemory(config, answers))) {
    const path = join(root, ".DNA", "CellularMemory", relPath);
    await writeFileEnsured(path, content);
    created.push(`.DNA/CellularMemory/${relPath}`);
  }

  for (const [file, content] of Object.entries(generateWorkflows(config.ci?.coverageThreshold ?? 80))) {
    const path = join(root, ".DNA", "workflows", file);
    await writeFileEnsured(path, content);
    created.push(`.DNA/workflows/${file}`);
  }

  for (const [relPath, content] of Object.entries(generateTemplateFiles())) {
    const path = join(root, ".DNA", relPath);
    await writeFileEnsured(path, content);
    created.push(`.DNA/${relPath}`);
  }

  // Runtime database (replaces legacy JSONL logs)
  const db = await ensureRuntimeDatabase(root);
  created.push(db.path);

  // Ensure all impression paths exist (fallback empty)
  for (const relPath of IMPRESSIONS_PATHS) {
    const path = join(root, "DNA", "Impressions", relPath);
    const { fileExists } = await import("../fs.js");
    if (!(await fileExists(path))) {
      await writeFileEnsured(path, `# ${relPath}\n\n_Generated by DNA by Humaan._\n`);
      created.push(`DNA/Impressions/${relPath}`);
    }
  }

  // Ensure behaviour dir has all files
  for (const file of BEHAVIOUR_FILES) {
    const path = join(root, ".DNA", "behaviour", file);
    const { fileExists } = await import("../fs.js");
    if (!(await fileExists(path))) {
      await writeFileEnsured(path, `# ${file}\n\n_Generated by DNA by Humaan._\n`);
      created.push(`.DNA/behaviour/${file}`);
    }
  }

  // Ensure cellular memory regions
  for (const region of CELLULAR_MEMORY_REGIONS) {
    const dir = join(root, ".DNA", "CellularMemory", region);
    const { ensureDir } = await import("../fs.js");
    await ensureDir(dir);
  }

  return created;
}
